import random
# This code allows us to use range values for item tables that, when passed through this function, creates a dictionary that has a separate entry for each item within the range.
#   For example: expand({range(1,4): "Dick"}, range(4,6): "Pennis", 6: "Balls")
#   Would give: {1: "Dick", 2: "Dick", 3: "Dick", 4: "Pennis", 5: "Pennis", 6: "Balls"}
def expand(d):
    ret = {}
    for k in d:
        v = d[k]
        if isinstance(k, range):
            ret.update({i: v for i in k})
        else:
            ret[k] = v
    return ret

def dice(dicestring):
    if "+" in dicestring:
        dicestring, mods = dicestring.split('+')
    else:
        mods = 0
    throws, sides = [int(_) for _ in dicestring.split('d')]
    return sum([int(mods), sum([random.randint(1, sides) for _ in range(throws)])])

encounter_artic_1_4 = expand({
             1: "1 Giant Owl",
    range(2,5):   f"{dice('1d6') + 3} Kobolds",
    range(6,8):   f"{dice('1d4') + 3} Trappers",
    range(9,10):   "1 Owl",
    range(11,12): f"{dice('2d4')} Blood hawks",
    range(13,17): f"{dice('2d6')} Bandits",
    range(18,20): f"{dice('1d3')} winged kobolds with {dice('1d6')} kobolds",
    range(21,25): f"The partially eaten carcass of a mammoth, from which f{dice('1d6')} weeks of rations can be harvested",
    range(26,29): f"{dice('2d8')} hunters (tribal warriors)",
    range(30,35):  "1 half ogre",
    range(36,40):  "Single-file tracks in the snow that stop abruptly",
    range(41,45): f"{dice('1d3')} ice mephits",
    range(46,50):  "1 brown bear",
    range(51,53): f"{dice('1d6') + 1} orcs",
    range(54,55):  "1 polar bear ",
    range(56,57): f"{dice('1d6')} scouts ",
    range(58,60):  "1 saber-toothed tiger",
    range(61,65):  "A frozen pond with a jagged hole in the ice that appears recently made",
    range(66,68):  "1 berserker",
    range(69,70):  "1 ogre",
    range(71,72):  "1 griffon",
    range(73,75):  "1 druid",
    range(76,80): f"{dice('3d4')} refugees (commoners) fleeing from ores",
              81: f"{dice('1d3')} veterans", 82: f"{dice('1d4')} orogs", 83:  "2 brown bears",
              84: f"1 ore Eye ofGruumsh with {dice('2d8')} ores",  85: f"{dice('1d3')} winter wolves",
    range(86,88): f"{dice('1d4')} yetis",
              88:  "1 half-ogre", 89: f"{dice('1d3')} manticores", 90: f"1 bandit captain with {dice('2d6')} bandits",
              91:  "1 revenant",
    range(92,93):  "1 troll",
    range(94,95):  "1 werebear",
    range(96,97):  "1 young remorhaz",
              98:  "1 mammoth", 99:  "1 young white dragon", 100:  "1 frost giant"
})

encounter_artic_5_10 = expand({
    range(1,5): "2 saber-toothed tigers" ,
    range(6,7): f"{dice('1d4')} half.ogres ",
    range(8,10): f"{dice('1d3') + 1} brown bears ",
    range(11,15): f"{dice('1d3')} polar bears ",
    range(16,20): f"{dice('2d4')} berserkers",
    range(21,25): "A half-ore druid tending to an injured polar bear. If the characters assist the druid, she gives them a vial of antitoxin.",
    range(26,30): f"{dice('2d8')} scouts ",
    range(31,35): f"{dice('2d4')} ice mephits",
    range(36,40): f"{dice('2d6') + 1} zombies aboard a galleon trapped in the ice. Searching the ship yields {dice('2d20')} days of rations.",
    range(41,45): "1 manticore",
    range(46,50): f"{dice('2d6') + 3} ores",
    range(51,53): f"{dice('1d6') + 2} ogres",
    range(54,55): f"{dice('2d4')} griffons ",
    range(56,57): f"{dice('1d4')} veterans ",
    range(58,60): f"1 bandit captain with 1 druid, {dice('1d3')} berserkers, and {dice('2d10') + 5} bandits ",
    range(61,65): f"{dice('1d4')} hours of extreme cold ",
    range(66,68): "1 young remorhaz ",
    range(69,72): f"1 ore Eye ofGruumsh with {dice('1d6')} orogs and {dice('2d8') + 6} ores ",
    range(73,75): "1 revenant ",
    range(76,80): f"A howl that echoes over the land for {dice('1d3')} minutes ",
    range(81,82): f"{dice('1d3')} mammoths ",
    range(83,84): "1 young white dragon ",
    range(85,86): f"{dice('2d4')} winter wolves ",
    range(87,88): f"{dice('1d6') + 2} yetis ",
    range(89,90): f"{dice('1d2')} frost giants ",
    range(91,92): f"{dice('1d3')} werebears ",
    range(93,94): f"{dice('1d4')} trolls ",
    range(95,96): "1 abominable yeti ",
    range(97,98): "1 remorhaz ",
              99: "1 roe ",
             100: f"{dice('2d4')} young remorhazes"
    })
encounter_artic_11_16 = expand ({
    1: "1 abominable yeti",
    range(2,4): f"{dice('1d6')} revenants", 
    range(5,10): f"{dice('1d4') + 1} werebears", 
    range(11,20): f"{dice('1d3')} young white dragons", 
    range(21,25): f"A blizzard that reduces visibility to 5 feet for {dice('1d6')} hours", 
    range(26,35): "1 roe ",
    range(36,40): f"A herd of {dice('3d20') + 60} caribou (deer) moving through the snow", 
    range(41,50): f"{dice('1d4')} mammoths ",
    range(51,60): f"{dice('1d8') + 1} trolls ",
    range(61,65): "A mile-wide frozen lake in which the preserved corpses of strange creatures can be seen ",
    range(66,75): f"{dice('2d4')} young remorhazes ",
    range(76,80): "A crumbling ice castle littered with the frozen bodies of blue-skinned humanoids ",
    range(81,90): "1 adult white dragon ",
    range(91,96): f"{dice('1d8') + 1} frost giants ",
    range(97,99): f"{dice('1d4')} remorhazes ",
    100: "1 ancient white dragon"
})
encounter_artic_17_20 = expand ({
    range(1,2): f"{dice('2d10')} revenants",
    range(3,4): f"{dice('2d8')} trolls",
    range(5,6): f"{dice('2d10')} werebears ",
    range(7,8): f"1 frost giant",
    range(9,10): f"{dice('2d4')} young remorhazes ",
    range(11,20): f"{dice('1d4')} frost giants",
    range(21,25): f"A circular patch of black ice on the ground. The air temperature around the patch is warmer than in the surrounding area, and characters who inspect the ice find bits of machinery frozen within.",
    range(26,35): f"1 ancient white dragon ",
    range(36,40): f"An adventurer frozen 6 feet under the ice; 50% chance the corpse has a rare magic item of the DM's choice ",
    range(41,50): f"{dice('1d3')} abominable yetis ",
    range(51,60): f"{dice('1d4')} remorhazes ",
    range(61,65): f"A 500-foot-high wall of ice that is 300 feet thick and spread across {dice('1d4')} miles ",
    range(66,75): f"{dice('1d4')} roes ",
    range(76,80): f"The likeness of a stern woman with long, flowing hair, carved into the side of a mountain ",
    range(81,90): f"{dice('1d10')} frost giants with {dice('2d4')} polar bears ",
    range(91,96): f"{dice('1d3')} adult white dragons ",
    range(97,99): f"{dice('2d4')} abominable yetis ",
    100: f"1 ancient white dragon with {dice('1d3')} young white dragons"
})
encounter_coastal_1_4 = expand({
    1: f"1 pseudodragon",
    range(2,5): f"{dice('2d8')} crabs",
    range(6,10): f"{dice('2d6')} fishers (commoners)",
    11: f"{dice('1d3')} poisonous snakes",
    range(12,13): f"{dice('1d6')} guards protecting a stranded noble ",
    range(14,15): f"{dice('2d4')} scouts ",
    range(16,18): f"{dice('2d10')} merfolk ",
    range(19,20): f"{dice('1d6') + 2} sahuagin ",
    range(21,25): f"{dice('1d4')} ghouls feeding on corpses aboard the wreckage of a merchant ship. A search uncovers {dice('2d6')} bolts of ruined silk, a 50-foot length of rope, and a barrel of salted herring. ",
    range(26,27): f"{dice('1d4')} winged kobolds with {dice('1d6') + 1} kobolds ",
    range(28,29): f"{dice('2d6')} tribal warriors ",
    range(30,31): f"{dice('3d4')} kobolds ",
    range(32,33): f"{dice('2d4') + 5} blood hawks ",
    range(34,35): f"{dice('1d8') + 1} pteranodons ",
    range(36,40): f"A few dozen baby turtles struggling to make their way to the sea ",
    range(41,42): f"{dice('1d6') + 2} giant lizards",
    range(43,44): f"{dice('1d6') + 4} giant crabs ",
    range(45,46): f"{dice('2d4')} stirges",
    range(47,48): f"{dice('2d6') + 3} bandits ",
    range(49,53): f"{dice('2d4')} sahuagin ",
    range(54,55): f"{dice('1d6') + 2} scouts",
    range(56,60): f"1 sea hag ",
    range(61,65): f"A momentary formation in the waves that looks like an enormous humanoid face ",
    range(66,70): f"1 druid ",
    range(71,75): f"{dice('1d4')} harpies ",
    range(76,80): f"A lone hermit (acolyte) sitting on the beach, contemplating the meaning of the multiverse ",
    81: f"{dice('1d4')} berserkers ",
    82: f"{dice('1d6')} giant eagles ",
    83: f"{dice('2d4')} giant toads ",
    84: f"{dice('1d4')} ogres or {dice('1d4')} merrow ",
    85: f"{dice('3d6')} sahuagin ",
    86: f"{dice('1d4')} veterans ",
    87: f"{dice('1d2')} plesiosauruses ",
    88: f"1 bandit captain with {dice('2d6')} bandits ",
    89: f"{dice('1d3')} manticores ",
    90: f"1 banshee ",
    range(91,92): f"{dice('1d4') + 3} griffons ",
    range(93,94): f"1 sahuagin priestess with {dice('1d3')} merrow and {dice('2d6')} sahuagin ",
    range(95,96): f"1 sahuagin baron ",
    range(97,98): f"1 water elemental ",
    99: f"1 cyclops ",
    00: f"1 young bronze dragon"
})
encounter_coastal_5_10 = expand ({
    1: f"{dice('2d8')} giant wolf spiders", 
    range(2,3): f"{dice('3d6')} pteranodons", 
    range(4,5): f"{dice('2d4')} scouts", 
    range(6,7): f"{dice('1d6') + 2} sahuagin", 
    8: f"1 sea hag", 
    range(9,10): f"{dice('1d4') + 1} giant toads", 
    range(11,15): f"{dice('3d6')} sahuagin", 
    range(16,20): f"{dice('2d6')} giant eagles", 
    range(21,25): f"A pseudodragon chasing gulls through the air", 
    range(26,29): f"{dice('1d2')} druids", 
    range(30,32): f"{dice('2d4') + 1} giant toads", 
    range(33,35): f"1 commoner singing a dirge day only or 1 banshee night only",
    range(36,40): f"A stoppered bottle containing an illegible note and half buried in the sand", 
    range(41,43): f"3 sea hags", 
    range(44,46): f"{dice('1d8') + 1} harpies", 
    range(47,50): f"{dice('1d4')} plesiosauruses", 
    range(51,53): f"{dice('1d4')} manticores", 
    range(54,56): f"{dice('2d4')} ogres", 
    range(57,60): f"{dice('1d10')} griffons", 
    range(61,65): f"A battle at sea between two galleons", 
    range(66,70): f"{dice('1d4') + 3} merrow", 
    range(71,75): f"A pirate crew consisting of 1 bandit captain, 1 druid, 2 berserkers, and {dice('2d12')} bandits, all searching for buried treasure", 
    range(76,80): f"A severed humanoid hand tangled in a net", 
    range(81,82): f"1 water elemental", 
    range(83,84): f"1 cyclops",
    range(85,86): f"{dice('1d4')} banshees (night only)", 
    range(87,88): f"{dice('2d4')} veterans",
    range(89,90): f"1 young bronze dragon", 
    range(91,93): f"{dice('1d3')} cyclopes",
    range(94,95): f"1 young blue dragon", 
    96: f"1 sahuagin baron with {dice('1d3')} sahuagin priestesses and {dice('2d8')} sahuagin", 
    97: f"1 djinni", 
    98: f"1 roe", 
    99: f"1 marid", 
    100: f"1 storm giant"
})
encounter_coastal_11_16 = expand({
    1: f"{dice('1d4')} banshees (night only)", 
    range(2,4): f"1 cyclops", 
    range(5,8): f"{dice('1d6') + 2} manticores", 
    range(9,10): f"{dice('1d8') + 2} veterans", 
    range(11,20): f"1 young blue dragon", 
    range(21,25): f"A nest of {dice('1d6')} dragon turtle eggs", 
    range(26,35): f"{dice('1d4')} sahuagin barons", 
    range(36,40): f"A trident partially buried in the sand", 
    range(41,50): f"1 young bronze dragon", 
    range(51,55): f"1 marid", 
    range(56,60): f"{dice('1d6')} water elementals", 
    range(61,65): f"{dice('2d6')} ghasts crawling over {dice('1d6')} wrecked ships and feeding on the dead", 
    range(66,70): f"1 djinni", 
    range(71,75): f"{dice('1d3')} young bronze dragons", 
    range(76,80): f"A beached whale, dead and bloated. If it takes any damage, it explodes, and each creature within 30 feet of it must make a DC 15 Dexterity saving throw, taking {dice('5d6')} bludgeoning damage on a failed save, or half as much damage on a successful one.", 
    range(81,82): f"{dice('2d4')} cyclopes", 
    range(83,84): f"1 storm giant",
    range(85,86): f"{dice('1d3')} young blue dragons",
    range(87,88): f"1 adult bronze dragon", 
    range(89,90): f"1 adult blue dragon", 
    range(91,93): f"{dice('1d3')} roes", 
    range(94,97): f"1 dragon turtle", 
    range(98,99): f"1 ancient bronze dragon", 
    100: f"1 ancient blue dragon"
})
encounter_coastal_17_20 = expand({
    range(1,10): f"1 roe", 
    range(11,20): f"1 storm giant", 
    range(21,25): f"An adult bronze dragon fighting an adult blue dragon to the death", 
    range(26,40): f"{dice('2d6')} cyclopes", 
    range(41,50): f"1 adult bronze dragon or 1 adult blue dragon", 
    range(51,60): f"{dice('1d3')} djinn or {dice('1d3')} marids", 
    range(61,70): f"1 dragon turtle", 
    range(71,75): f"{dice('1d3')} roes", 
    range(76,80): f"{dice('1d6') + 2} waterspouts that dance on the water before stopping abruptly", 
    range(81,90): f"{dice('1d6')} young blue dragons",
    range(91,96): f"1 ancient bronze dragon", 
    range(97,99): f"1 ancient blue dragon", 
    100: f"{dice('1d3') + 1} storm giants"
})
encounter_desert_1_4 = expand({
    1: f"{dice('3d8')} scorpions",
    2: f"{dice('2d4')} vultures",
    3: f"1 abandoned mule",
    4: f"{dice('2d6')} commoners with {dice('2d4')} camels bound for a distant city",
    5: f"{dice('1d6')} flying snakes",
    6: f"{dice('2d6')} hyenas or {dice('2d6')} jackals",
    7: f"{dice('1d6')} guards escorting a noble to the edge of the desert,all of them astride camels",
    8: f"{dice('1d6')} cats",
    9: f"1 pseudodragon",
    10: f"{dice('1d4')} poisonous snakes",
    range(11,13): f"{dice('2d4')} stirges",
    range(14,15): f"{dice('1d6') + 2} giant wolf spiders",
    range(16,17): f"1 scout",
    range(18,20): f"{dice('2d4')} giant poisonous snakes",
    range(21,25): f"Singlefile tracks marching deeper into the desert",
    range(26,27): f"{dice('4d4')} koboIds",
    range(28,29): f"1 jackalwere",
    range(30,31): f"{dice('3d6')} tribal warriors",
    range(32,33): f"{dice('1d6')} giant lizards ",
    range(34,35): f"1 swarm of insects ",
    range(36,40): f"An oasis surrounded by palm trees and containing the remnants of an oId camp ",
    range(41,44): f"{dice('3d6')} bandits ",
    range(45,46): f"{dice('1d4')} constrictor snakes ",
    range(47,48): f"{dice('2d4')} winged koboIds ",
    range(49,50): f"1 dust mephit ",
    range(51,52): f"{dice('1d3') + 1} giant toads ",
    range(53,54): f"{dice('1d4')} giant spiders ",
    55: f" 1 druid ",
    range(56,57): f"{dice('2d4')} hobgoblins ",
    58: f" 1 wight ",
    range(59,60): f"1 ogre ",
    range(61,65): f"A brass lamp lying on the ground ",
    range(66,67): f"{dice('1d4')} giant vultures ",
    68: f"1 phase spider ",
    69: f"1 giant constrictor snake ",
    range(70,71): f"1 gnoll pack lord with {dice('1d3')} giant hyenas ",
    72: f"{dice('1d6') + 2} gnolls ",
    range(73,74): f"1 mummy ",
    75: f"{dice('1d3')} half ogres ",
    range(76,80): f"A pile of humanoid bones wrapped in rotting cloth ",
    range(81,82): f"1 lamia ",
    83: f" 1 hobgoblin captain with {dice('2d6')} hobgoblins ",
    84: f"{dice('2d4')} death dogs",
    range(85,86): f"{dice('1d4')} giant scorpions ",
    87: f"1 yuan ti malison with {dice('1d4') + 1} yuan ti purebloods ",
    range(88,89): f"1 bandit captain with 1 druid and {dice('3d6')} bandits ",
    90: f"{dice('2d4')} thri kreen ",
    91: f"1 air elemental ",
    92: f"{dice('1d3')} couatls ",
    93: f"1 fire elemental ",
    94: f"{dice('1d4')} gnoll fangs of Yeenoghu ",
    95: f"1 revenant ",
    96: f"{dice('1d4')} weretigers ",
    97: f"1 cyclops ",
    98: f"1 young brass dragon ",
    99: f"1 medusa",
    100: f"1 yuan ti abomination"
})
encounter_desert_5_10 = expand({
    1: f"{dice('1d6')} scouts ",
    2: f"{dice('2d4')} jackalweres ",
    3: f"{dice('2d6')} hobgoblins ",
    4: f"{dice('1d4') + 3} dust mephits ",
    5: f"{dice('1d6')} swarms of insects ",
    6: f"1 giant constrictor snake",
    range(7,8): f"1 lion",
    range(9,10): f"{dice('2d4')} gnolls",
    range(11,12): f"{dice('2d6')} giant toads",
    range(13,17): f"1 mummy",
    range(18,20): f"{dice('1d8') + 1} giant vultures",
    range(21,25): f"A stone obelisk partly buried in the sand",
    range(26,28): f"1 ogre with {dice('1d3')} half ogres",
    range(29,35): f"{dice('1d10')} giant hyenas",
    range(36,40): f"{dice('1d6') + 1} empty tents",
    range(41,43): f"{dice('1d6') + 2} thri kreen",
    range(44,46): f"{dice('2d4')} yuan ti purebloods",
    range(47,50): f"{dice('1d6') + 3} death dogs",
    range(51,52): f"{dice('1d4')} giant scorpions",
    53: f"1 fire elemental",
    range(54,55): f"1 hobgoblin captain with {dice('3d4')} hobgoblins",
    56: f"{dice('1d6') + 2} ogres",
    range(57,58): f"{dice('1d4')} lamias",
    range(59,60): f"1 air elemental",
    range(61,65): f"A meteorite resting at the bottom of a glassy crater",
    66: f"{dice('1d4') + 1} wights",
    range(67,68): f"1 young brass dragon",
    range(69,70): f"1 bandit captain with {dice('1d3')} berserkers and {dice('3d6')} bandits",
    range(71,72): f"1 cyclops",
    73: f"{dice('1d4')} couatls",
    range(74,75): f"{dice('1d4')} yuan ti malisons",
    range(76,80): f"Strong winds that kick up dust and reduce visibility to {dice('1d6')} feet for {dice('1d4')} hours",
    range(81,83): f"1 revenant with {dice('1d3')} wights",
    range(84,85): f"{dice('1d8') + 1} phase spiders",
    range(86,87): f"{dice('1d6') + 2} weretigers",
    range(88,90): f"{dice('2d4')} gnoll fangs ofYeenoghu",
    91: f"1 young blue dragon",
    92: f"{dice('1d4')} cyclopes",
    93: f"{dice('1d3')} yuan ti abominations",
    94: f"{dice('1d4')} medusas",
    95: f"1 guardian naga",
    96: f"{dice('1d3')} young brass dragons",
    97: f"1 efreeti",
    98: f"1 roe",
    99: f"1 gynosphinx",
    100: f"1 adult brass dragon"
})
encounter_desert_11_16 = expand({
    1: f"1 yo_ung brass dragon",
    range(2,5): f"{dice('4d6')} gnolls",
    range(6,10): f"{dice('3d10')} giant hyenas",
    range(11,12): f"{dice('1d8') + 1} lamias",
    range(13,14): f"{dice('2d4')} gnoll fangs ofYeenoghu",
    range(15,17): f"{dice('1d6') + 2} giant scorpions",
    range(18,20): f"{dice('2d4')} phase spiders",
    range(21,25): f"A desert caravan consisting of {dice('1d6')} merchants (nobles) with {dice('2d6')} guards",
    range(26,27): f"{dice('1d6') + 1} couatls",
    range(28,30): f"{dice('1d4')} fire elementals",
    range(31,32): f"1 hobgoblin captain with {dice('3d10') + 10} hobgoblins",
    range(33,35): f"{dice('2d4')} wights",
    range(36,40): f"{dice('1d6')} square miles of desert glass",
    range(41,42): f"1 young blue dragon",
    range(43,45): f"{dice('1d6') + 2} weretigers",
    range(46,48): f"{dice('1d4')} air elementals ",
    range(49,50): f"{dice('1d6') + 1} yuan ti malisons ",
    range(51,55): f"{dice('1d4')} medusas ",
    range(56,60): f"{dice('1d4')} revenants with {dice('3d12')} skeletons ",
    range(61,65): f"A plundered pyramid ",
    range(66,70): f"{dice('1d4')} young brass dragons ",
    range(71,75): f"{dice('1d3')} yuan ti abominations ",
    range(76,78): f"{dice('1d6') + 2} cyclopes ",
    range(79,82): f"1 adult brass dragon ",
    range(83,85): f"1 purple worm ",
    86: f"{dice('1d2')} young blue dragons ",
    range(87,88): f"1 mummy lord ",
    89: f"{dice('1d3')} guardian nagas ",
    90: f"1 adult blue dragon ",
    91: f"{dice('1d2')} gynosphinxes ",
    range(92,93): f"{dice('1d3')} efreet ",
    94: f"1 androsphinx ",
    95: f"{dice('1d4')} roes ",
    range(96,97): f"1 adult blue dracolich ",
    range(98,99): f"1 ancient brass dragon ",
    100: f"1 ancient blue dragon",
})
encounter_desert_17_20 = expand({
    range(1,5): f"1 adult brass dragon ",
    range(6,10): f"{dice('1d2')} yuan ti abominations with {dice('2d10') + 5} yuan ti malisons and {dice('4d6') + 6} yuan ti purebloods ",
    range(11,14): f"{dice('1d6') + 2} medusas ",
    range(15,18): f"{dice('1d2')} purple worms ",
    range(19,22): f"{dice('2d4')} cyclopes ",
    range(23,25): f"An abandoned city made from white marble,empty during the day. At night,harmless apparitions roam the streets,replaying the final moments of their lives. ",
    range(26,30): f"{dice('1d3')} young blue dragons ",
    range(31,35): f"1 mummy lord ",
    range(36,40): f"{dice('1d4')} hours of extreme heat",
    range(41,50): f"{dice('1d3')} guardian nagas ",
    range(51,60): f"{dice('1d4')} efreet ",
    range(61,63): f"An oId signpost identifying a single destination,called Pazar ",
    range(64,72): f"{dice('1d4')} roes ",
    range(73,80): f"{dice('1d3')} gynosphinxes ",
    range(81,85): f"1 adult blue dracolich ",
    range(86,90): f"1 androsphinx ",
    range(91,96): f"1 ancient brass dragon ",
    range(97,99): f"1 ancient blue dragon ",
    100: f"{dice('1d4')} adult brass dragons",
})
encounter_forest_1_5 = expand({
    1: f"1 giant owl",
    2: f"{dice('1d4')} cats",
    3: f"{dice('2d4')} woodcutters (commoners)",
    4: f"1 badger or {dice('1d4')} poisonous snakes",
    5: f"{dice('2d8')} baboons",
    6: f"{dice('1d6') + 3} hyenas",
    7: f"1 owl",
    8: f"1 pseudodragon",
    9: f"1 panther",
    10: f"1 giant poisonous snake",
    11: f"{dice('1d6') + 2} boars",
    12: f"{dice('1d4') + 1} giant lizards",
    13: f"1 ape or 1 tiger",
    14: f"{dice('2d6')} tribal warriors with {dice('1d6')} mastiffs",
    15: f"{dice('1d6') + 2} giant bats or {dice('3d6')} flying snakes",
    16: f"1 scout or {dice('2d4')} guards with {dice('1d8')} mastiffs",
    17: f"{dice('1d8') + 1} winged koboIds",
    18: f"{dice('1d3')} constrictor snakes",
    19: f"{dice('1d10') + 5} giant rats or {dice('2d6') + 3} giant weasels",
    20: f"{dice('1d4') + 1} needle blights with {dice('1d6') + 3} twig blights",
    range(21,25): f"A lost,weeping chiId. If the characters take the chiId home,the parents rewa rd them with {dice('1d3')} potions of healing.",
    26: f"{dice('1d8') + 1} giant frogs",
    27: f"{dice('4d4')} koboIds",
    28: f"{dice('1d3')} black bears",
    29: f"{dice('3d6')} stirges",
    30: f"1 satyr",
    31: f"{dice('2d4')}kenku",
    32: f"{dice('1d3')} vine blights with {dice('1d12')} awakened shrubs",
    33: f"{dice('1d4')} swarms of ravens",
    34: f"1 faerie dragon (yellow or younger)",
    35: f"{dice('1d4') + 2} giant badgers",
    range(36,40): f"A young woodcutter (scout) racing through the forest to rescue a lost friend",
    41: f"{dice('2d4')} blink dogs",
    42: f"{dice('1d8') + 1} sprites",
    43: f"{dice('1d6')} + 2 elk",
    44: f"{dice('1d4')} lizardfolk or {dice('3d6')} bandits",
    45: f"{dice('1d4') + 4} wolves",
    46: f"{dice('2d4')} giant wolf spiders",
    47: f"1 swarm of insects or {dice('2d8')} blood hawks",
    48: f"{dice('1d6') + 2} pixies",
    49: f"1 brown bear",
    50: f"{dice('1d4') + 3} goblins",
    51: f"{dice('1d3')} dryads",
    52: f"1 awakened tree",
    53: f"1 phase spider",
    54: f"{dice('1d6')} harpies",
    55: f"1 ettercap or {dice('1d8') + 1} ores",
    56: f"1 goblin boss with {dice('2d6') + 1} goblins",
    57: f"1 ankheg",
    58: f"1 giant constrictor snake",
    59: f"{dice('1d4')} bugbears or {dice('2d4')} hobgoblins",
    60: f"1 pegasus",
    range(61,65): f"A stream of cool,clean water flowing between the trees",
    66: f"{dice('1d4')} half orgres or 1 ogre",
    67: f"1 faerie dragon (green or oIder)",
    68: f"1 werewolf or {dice('1d8') + 1} worgs",
    69: f"1 druid harvesting mistletoe",
    70: f"1 will o'wisp",
    71: f"{dice('1d4')} dire wolves or 1 giant boar",
    72: f"{dice('1d10')} giant wasps",
    73: f"1 owlbear or 1 giant elk",
    74: f"{dice('2d6')} gnolls",
    75: f"{dice('1d6')} giant toads",
    range(76,80): f"{dice('1d6')} web cocoons hanging from the branches,hoIding withered carcasses",
    81: f"1 wereboar or {dice('1d4')} giant boars",
    82: f"{dice('1d6') + 2} giant spiders",
    83: f"{dice('1d4')} centaurs or {dice('1d4')} giant elk",
    84: f"1 ore Eye ofGruumsh with {dice('2d4') + 2} ores",
    85: f"1 gnoll fang ofYeenoghu",
    86: f"{dice('1d4')} gricks",
    87: f"1 bandit captain with {dice('2d6') + 3} bandits",
    88: f"{dice('1d4')} wererats",
    89: f"1 couatl (day) Or 1 banshee (night)",
    90: f"1 gnoll pack lord with {dice('1d4')} giant hyenas",
    91: f"{dice('2d4')} berserkers or {dice('1d4')} veterans",
    92: f"1 lizardfofk shaman with {dice('1d3')} swarms of poisonous snakes and {dice('1d10') + 2} lizardfolk",
    93: f"{dice('1d4')} displacer beasts",
    94: f"{dice('1d3')} green hags",
    95: f"1 hobgoblin captain with {dice('2d6')} hobgoblins and {dice('1d4')} giant boars",
    96: f"1 yuan ti malison with {dice('1d6') + 1} yuan ti purebloods",
    97: f"{dice('1d3')} weretigers",
    98: f"1 gorgon or 1 unicorn",
    99: f"1 shambling mound",
    100: f"1 yuan ti abomination",
})
encounter_forest_5_10 = expand({
    1: f"{dice('2d4')} vine blights",
    2: f"{dice('2d6')} hobgoblins or {dice('2d6')} ores",
    3: f"{dice('2d4')} apes or {dice('2d4')} satyrs",
    4: f"{dice('1d3')} will o'wisps",
    5: f"{dice('1d4')} swarms of poisonous snakes",
    6: f"1 ore Eye ofGruumsh with {dice('1d3')} orogs and {dice('1d8') + 2} ores",
    7: f"{dice('1d3')} constrictor snakes or {dice('1d4')} tigers",
    8: f"1 goblin boss with {dice('3d6')} goblins",
    9: f"1 faerie dragon (any age)",
    10: f"1 brown bear or {dice('1d6') + 2} black bears",
    range(11,13): f"{dice('1d4')} giant boars",
    range(14,15): f"{dice('1d8') + 1} giant spiders",
    range(16,17): f"1 lizardfolk shaman with {dice('2d4')} lizardfolk",
    18: f"{dice('1d10')} giant toads",
    19: f"{dice('1d4')} ankhegs",
    20: f"{dice('1d3')} awakened trees (day) Or 1 banshee (night)",
    range(21,25): f"A small shack almost hidden by the deep forest. The interior is empty aside from a large cast iron oven.",
    26: f"1 couatl",
    range(27,28): f"{dice('1d4')} ogres or {dice('1d6') + 2} half.ogres",
    range(29,30): f"1 gnoll pack lord with {dice('1d4') + 1} giant hyenas",
    range(31,32): f"{dice('1d6')} wererats",
    33: f"{dice('1d4')} gricks",
    34: f"{dice('1d8') + 1} yuan ti purebloods",
    35: f"{dice('1d6')} pegasi",
    range(36,40): f"An oId stone archway of obvious elven design. Any character who passes under it makes Wisdom (Perception) checks with advantage for 1 hour.",
    range(41,42): f"{dice('1d6') + 2} dryads",
    43: f"{dice('1d4')} giant elk",
    44: f"{dice('1d8') + 1} harpies",
    range(45,46): f"1 bandit captain with 1 druid and {dice('1d6') + 5} bandits",
    range(47,48): f"{dice('2d4')} dire wolves",
    range(49,50): f"{dice('2d4')} bugbears",
    range(51,52): f"{dice('2d4')} centaurs",
    range(53,54): f"{dice('3d10')} blink dogs",
    range(55,56): f"{dice('1d4')} owl bears",
    range(57,58): f"{dice('1d8') + 1} berserkers",
    range(59,60): f"{dice('1d3')} green hags",
    range(61,65): f"A clear pool of water with {dice('1d6')} sleeping animals lying around its edge",
    range(66,67): f"{dice('1d4')} werewolves",
    range(68,69): f"1 werebear",
    range(70,71): f"{dice('1d8') + 1} ettercaps",
    range(72,73): f"{dice('2d10')} elk",
    range(74,75): f"{dice('1d4')} veterans",
    range(76,80): f"An oId tree with a wizened face carved into the trunk",
    81: f"{dice('1d4')} wereboars",
    82: f"{dice('2d4')} displacer beasts",
    83: f"{dice('1d4')} shambling mounds",
    84: f"1 hobgoblin captain with {dice('3d10')} hobgoblins and {dice('4d12')} goblins",
    85: f"1 yuan ti abomination",
    86: f"{dice('1d8') + 1} phase spiders",
    87: f"{dice('1d4')} trolls",
    88: f"{dice('2d4')} yuan ti malisons",
    89: f"1 oni",
    90: f"{dice('1d4')} unicorns",
    91: f"{dice('1d6') + 2} weretigers",
    92: f"1 young green dragon",
    93: f"{dice('1d4')} gorgons",
    94: f"{dice('1d6') + 2} gnoll fangs ofYeenoghu",
    95: f"1 treant",
    96: f"{dice('1d4')} revenants",
    97: f"1 grick a lpha with {dice('1d6') + 1} gricks",
    98: f"{dice('1d4')} giant apes",
    99: f"1 guardian naga",
    100: f"1 adult goId dragon"
})
encounter_forest_11_16 = expand({
    range(1,3): f"1 werebear",
    range(4,5): f"{dice('1d4')} druids performing a ritual for the dead (day only) Or {dice('1d4')} banshees (night only)",
    range(6,7): f"{dice('1d3')} couatls",
    range(8,10): f"{dice('1d3')} gnoll fangs ofYeenoghu with {dice('2d6') + 3} gnolls",
    range(11,15): f"{dice('2d4')} displacer beasts",
    range(16,20): f"{dice('1d6') + 2} veterans",
    range(21,25): f"A pool of clear,still water. goId coins litter the bottom,but they disappear if removed from the pool.",
    range(26,30): f"{dice('1d4') + 1} green hags with {dice('1d3')} owlbears",
    range(31,35): f"{dice('1d6') + 2} werewolves",
    range(36,40): f"A small woodland shrine dedicated to a mysterious cult named the Siswa",
    range(41,45): f"{dice('1d6') + 2} phase spiders",
    range(46,50): f"{dice('2d4')} yuan ti malisons",
    range(51,52): f"{dice('1d3')} werebears",
    range(53,54): f"{dice('1d4')} revenants",
    range(55,56): f"1 young green dragon",
    range(57,58): f"{dice('1d4')} trolls",
    range(59,60): f"{dice('1d6') + 2} wereboars",
    range(61,65): f"A group of seven people (commoners) wearing animal masks and ambling through the woods",
    range(66,67): f"{dice('1d4')} gorgons",
    range(68,69): f"{dice('1d3')} shambling mounds",
    range(70,71): f"1 treant",
    range(72,73): f"{dice('1d4')} unicorns",
    range(74,75): f"{dice('1d6') + 2} weretigers",
    range(76,80): f"Peals of silvery laughter that echo from a distance",
    range(81,82): f"1 guardian naga",
    range(83,84): f"1 young goId dragon",
    range(85,86): f"1 grick alpha with {dice('2d4')} gricks",
    range(87,88): f"{dice('1d3')} yuan ti abominations",
    range(89,90): f"1 adult green dragon",
    range(91,93): f"{dice('1d8') + 1} giant apes",
    range(94,96): f"{dice('2d4')} oni",
    range(97,99): f"{dice('1d3')} treants",
    100: f"1 ancient green dragon"
})
encounter_forest_17_20 = expand({
    range(1,5): f"1 young green dragon",
    range(6,10): f"1 treant",
    range(11,13): f"1 guardian naga",
    range(14,16): f"1 dl 0 revenants",
    range(17,19): f"{dice('1d8') + 1} unicorns",
    range(20,22): f"{dice('1d3')} grick alphas",
    range(23,25): f"For a few hundred feet,wherever the characters step,Aowers bloom and emit soft light.",
    range(26,28): f"1 young goId dragon",
    range(29,31): f"{dice('1d6') + 2} shambling mounds",
    range(32,34): f"{dice('2d4')} werebears",
    range(35,37): f"{dice('1d4')} oni",
    range(38,40): f"{dice('4d6') + 10} elves living in a small community in the treetops",
    range(41,43): f"{dice('1d6') + 2} gorgons",
    range(44,46): f"{dice('2d4')} trolls",
    range(47,49): f"{dice('1d4')} giant apes",
    range(50,52): f"{dice('1d3')} yuan ti abominations",
    range(53,62): f"{dice('1d3')} young green dragons",
    range(63,65): f"A 5O foot tall stone statue of an elf warrior with hand raised,palm out,as if to forbid travelers from coming this way",
    range(66,75): f"{dice('1d4')} treants",
    range(76,80): f"A cairn set atop a low hill",
    range(81,90): f"1 adult goId dragon",
    range(91,96): f"1 ancient green dragon",
    range(97,99): f"{dice('2d4') + 1} treants",
    100: f"1 ancient goId dragon"
})
encounter_grassland_1_5 = expand({
    1: f"1 hobgoblin captain with {dice('1d4') + 1} hobgoblins",
    2: f"1 chimera",
    3: f"1 gorgon",
    4: f"{dice('1d2')} couatls",
    5: f"1 ankylosaurus",
    6: f"1 weretiger",
    7: f"{dice('1d3')} allosauruses",
    range(8,9): f"{dice('1d3')} elephants",
    range(10,14): f"A circle of standing stones within which the air is utterly still,no matter how hard the wind blows outside",
    range(15,16): f"1 phase spider",
    range(17,18): f"1 gnoll pack lord with {dice('1d4')} giant hyenas",
    range(19,20): f"1 orog or 1 pegasus",
    range(21,22): f"1 ankheg",
    range(23,24): f"{dice('1d3')} rhinoceroses",
    range(25,28): f"{dice('1d3')} cockatrices",
    range(29,32): f"{dice('1d6') + 2} giant wasps or {dice('1d4') + 3} swarms of insects",
    range(33,36): f"{dice('1d4')} jackalweres or {dice('1d4')} scouts",
    range(37,40): f"{dice('1d8')} giant goats or {dice('1d8')} worgs",
    range(41,44): f"{dice('2d4')} hobgoblins,{dice('2d4')} ores,or {dice('2d4')} gnolls",
    range(45,46): f"{dice('1d2')} giant poisonous snakes",
    range(47,48): f"{dice('1d6') + 2} elk or {dice('1d6') + 2} riding horses",
    range(49,50): f"{dice('2d4')} goblins",
    range(51,52): f"{dice('1d3')} boars",
    range(53,54): f"1 panther (leopard) Or 1 lion",
    range(55,58): f"{dice('1d6') + 3} goblins riding wolves",
    range(59,62): f"{dice('2d6')} giant wolf spiders or 1 giant eagle",
    range(63,65): f"{dice('1d8') + 4} pteranodons",
    range(66,69): f"{dice('3d6')} wolves",
    range(70,74): f"{dice('2d4') + 2} axe beaks",
    range(75,76): f"1 giant boar or {dice('1d2')} tigers",
    range(77,78): f"1 ogre or {dice('1d3')} bugbears",
    range(79,80): f"1 giant elk,or 1 gnoll pack lord with {dice('1d3')} giant hyenas",
    range(81,82): f"{dice('1d3')} giant vultures or {dice('1d3')} hippogriffs",
    range(83,84): f"1 goblin boss with {dice('1d6') + 2} goblins and {dice('1d4') + 3} wolves,or {dice('1d3')} thri kreen",
    range(85,89): f"{dice('1d3')} druids patrolling the wiIds",
    range(90,91): f"{dice('1d6')} scarecrows or 1 wereboar",
    range(92,93): f"{dice('1d3')} centaurs or {dice('1d3')} griffons",
    94: f"{dice('1d3')} gnoll fangs ofYeenoghu,or 1 ore Eye of Gruumsh with {dice('2d4') + 1} ores ",
    range(95,96): f"1 triceratops",
    97: f"1 cyclops or 1 bulette",
    range(98,99): f"{dice('1d4')} manticores",
    100: f"1 tyrannosaurus rex"
})
encounter_grassland_6_10 = expand({
    1: f"{dice('1d3')} gorgons",
    2: f"{dice('1d4')} cyclopes",
    range(3,4): f"{dice('1d3')} gnoll fangs ofYeenoghu",
    range(5,6): f"1 chimera ",
    range(7,9): f"{dice('1d4') + 1} veterans on riding horses",
    range(10,11): f"A tornado that touches down {dice('1d6')} miles away,tearing up the land for 1 mile before it dissipates",
    range(12,13): f"{dice('1d3')} manticores",
    range(14,15): f"{dice('2d4')} ankhegs",
    range(16,17): f"{dice('1d8') + 1} centaurs",
    range(18,19): f"{dice('1d6') + 2} griffons",
    range(20,21): f"{dice('1d6')} elephants",
    range(22,24): f"A stretch of land littered with rotting war machines,bones,and banners of forgotten armies",
    range(25,28): f"{dice('1d8') + 1} bugbears",
    range(29,32): f"1 gnoll pack lord with {dice('1d4') + 1} giant hyenas",
    range(33,36): f"{dice('2d4')} scarecrows",
    range(37,40): f"{dice('1d12')} lions",
    range(41,44): f"{dice('1d10')} thri kreen",
    range(45,46): f"1 allosaurus",
    range(47,48): f"1 tiger",
    range(49,50): f"{dice('1d2')} giant eagles or {dice('1d2')} giant vultures",
    range(51,52): f"1 goblin boss with {dice('2d4')} goblins",
    range(53,54): f"{dice('1d2')} pegasi",
    range(55,58): f"1 ankylosaurus",
    range(59,62): f"{dice('1d2')} couatls",
    range(63,66): f"1 ore Eye ofGruumsh with {dice('1d8') + 1} ores",
    range(67,70): f"{dice('2d4')} hippogriffs",
    range(71,74): f"{dice('1d4') + 1} rhinoceroses",
    range(75,76): f"1 hobgoblin captain with {dice('2d6')} hobgoblins",
    range(77,78): f"{dice('1d3')} phase spiders",
    range(79,80): f"{dice('1d6') + 2} giant boars",
    range(81,82): f"{dice('2d4')} giant elk",
    range(83,84): f"{dice('1d4')} ogres and {dice('1d4')} orogs",
    range(85,87): f"A hot wind that carries the stench of rot",
    range(88,90): f"{dice('1d3')} weretigers",
    range(91,92): f"1 bulette",
    range(93,94): f"A tribe of {dice('2d20') + 20} nomads (tribal warriors) On riding horses following a herd of antelope (deer). The nomads are willing to trade food,leather,and information for weapons.",
    range(95,96): f"{dice('1d6') + 2} wereboars",
    97: f"1 young goId dragon",
    range(98,99): f"{dice('1d4')} triceratops",
    100: f"{dice('1d3')} tyrannosaurus rexes"
})
encounter_grassland_11_16 = expand({
    range(1,5): f"{dice('3d6')} wereboars",
    range(6,10): f"{dice('2d10')} gnoll fangs ofYeenoghu",
    range(11,15): f"{dice('1d4')} bulettes",
    range(16,17): f"An oId road of paved stones,partly reclaimed by wiIderness,that travels for {dice('1d8')} miles in either direction before ending",
    range(18,27): f"{dice('1d12')} couatls",
    range(28,30): f"A witch (mage) dwelling in a crude hut. She offers potions of healing,antitoxins,and other consumable items for sale in exchange for food and news.",
    range(31,40): f"{dice('2d10')} elephants",
    range(41,46): f"{dice('2d4')} weretigers",
    range(47,56): f"{dice('1d8') + 1} cyclopes",
    range(57,61): f"{dice('1d3')} chimeras",
    range(62,66): f"5 triceratops",
    range(67,69): f"A giant hole 50 feet across that descends nearly 500 feet before opening into an empty cave",
    range(70,79): f"{dice('1d4') + 3} gorgons",
    range(80,88): f"{dice('1d3')} young goId dragons",
    range(89,90): f"A circular section of grass nearly a quarter mile across that appears to have been pressed down; {dice('1d4')} more such circles connected by lines can be seen from overhead.",
    range(91,96): f"{dice('2d4')} tyrannosaurus rexes",
    range(97,99): f"1 adult goId dragon",
    100: f"1 ancient goId dragon"
})
encounter_grassland_17_20 = expand({
    range(1,10): f"{dice('2d6')} triceratops",
    range(11,20): f"{dice('1d10')} gorgons",
    range(21,25): f"{dice('2d6')} hyenas feed ing on the carcass of a dead dinosaur",
    range(26,35): f"{dice('3d6')} bulettes",
    range(36,40): f"A fiery chariot that races across the sky",
    range(41,50): f"{dice('1d3')} young goId dragons",
    range(51,60): f"{dice('2d4')} cyclopes",
    range(61,65): f"A valley where all the grass has died and the ground is littered with stumps and fallen tree trunks,all petrified",
    range(66,75): f"{dice('2d10')} bugbears with {dice('4d6')} goblins and {dice('2d10')} wolves",
    range(76,80): f"A friendly adventuring party of {dice('1d6') + 1} characters of varying races,classes,and levels (average level {dice('1d6') + 2}). They share information about their recent travels.",
    range(81,90): f"{dice('1d12')} chimeras",
    range(91,96): f"{dice('1d6') + 2} tyrannosaurus rexes",
    range(97,99): f"1 adult goId dragon",
    100: f"1 ancient goId dragon"
})
encounter_hills_1_4 = expand({
    1: f"1 eagle",
    range(2,3): f"{dice('2d4')} baboons",
    range(4,6): f"{dice('1d6')} bandits",
    7: f"{dice('1d4')} vultures",
    8: f"{dice('1d10')} commoners",
    9: f"1 raven",
    10: f"1 poisonous snake",
    range(11,13): f"{dice('2d6')} bandits or {dice('2d6')} tribal warriors",
    14: f"{dice('2d8')} goats",
    15: f"{dice('1d6') + 4} blood hawks",
    16: f"{dice('1d4') + 3} giant weasels",
    range(17,18): f"{dice('1d3')} guards with {dice('1d2')} mastiffs and 1 mule",
    range(19,20): f"{dice('1d6') + 5} hyenas",
    range(21,22): f"{dice('2d4')} stirges",
    range(23,25): f"An empty cave litte red with bones ",
    26: f"1 pseudodragon or {dice('1d3')} giant owls ",
    27: f"1 lion or 1 panther (cougar) ",
    range(28,30): f"{dice('2d8')} koboIds ",
    31: f"1 hippogriff ",
    range(32,34): f"{dice('2d4')} goblins ",
    35: f"1 worg ",
    36: f"{dice('1d3')} swarms of bats or {dice('1d3')} swarms of ravens ",
    37: f"1 giant eagle ",
    range(38,40): f"An oId dwarf sitting on a stump,whittling a piece of wood ",
    41: f"{dice('1d4')} elk ",
    42: f"{dice('1d4')} winged koboIds with {dice('1d6')} koboIds ",
    43: f"{dice('1d6') + 2} giant wolf spiders ",
    range(44,45): f"{dice('2d4')} wolves ",
    46: f"1 swarm ofinsects ",
    47: f"{dice('1d8') + 1} axe beaks ",
    range(48,49): f"1 brown bear or {dice('1d3')} boars",
    50: f"1 scout ",
    51: f"1 ogre ",
    range(52,53): f"{dice('2d4')} gnolls ",
    54: f"1 giant elk ",
    55: f"{dice('1d3') + 1} harpies ",
    56: f"1 werewolf ",
    range(57,58): f"{dice('2d4')} ores ",
    59: f"{dice('1d4')} half orgres ",
    60: f"1 druid or 1 veteran ",
    range(61,63): f"The corpse of an adventurer that carries an intact explorer's pack and lies atop a longsword",
    64: f"1 green hag ",
    range(65,66): f"{dice('1d3')} dire wolves ",
    range(67,68): f"A small cemetery containing {dice('2d6')} graves ",
    range(69,70): f"1 hobgoblin captain with {dice('2d4')} hobgoblins ",
    71: f"{dice('2d4')} giant goats ",
    72: f"1 manticore ",
    range(73,74): f"{dice('1d6') + 2} hobgoblins ",
    75: f"1 phase spider ",
    range(76,78): f"A pile of droppings from a very large bird ",
    79: f"1 gnoll fang ofYeenoghu ",
    80: f"{dice('1d3')} giant boars ",
    81: f"1 gnoll pack lord with {dice('1d3')} giant hyenas ",
    82: f"1 bandit captain wit h {dice('2d4')} bandits ",
    83: f"1 ore Eye ofGruumsh with {dice('1d8') + 2} ores ",
    84: f"{dice('1d3')} orogs or {dice('1d4')} berserkers ",
    range(85,86): f"1 ettin or 1 wereboar ",
    range(87,88): f"1 goblin boss with {dice('2d6')} goblins ",
    89: f"{dice('1d3')} griffons ",
    90: f"{dice('1d3')} perytons or {dice('1d4')} pegasi ",
    range(91,96): f"{dice('1d3')} trolls ",
    range(97,99): f"1 cyclops ",
    100: f"1 stone giant"

})
encounter_hills_5_10 = expand({
    1: f"{dice('1d4')} pegasi or {dice('1d3')} perytons",
    2: f"{dice('1d6') + 2} giant goats",
    3: f"1 manticore",
    4: f"{dice('1d8') + 1} gnolls or {dice('1d8') + 1} hobgoblins",
    5: f"{dice('1d4')} lions",
    6: f"{dice('1d6') + 2} worgs",
    7: f"{dice('1d4')} brown bears",
    8: f"{dice('3d6')} axe beaks",
    9: f"1 half ogre with {dice('2d6')} ores",
    10: f"{dice('2d10')} winged koboIds",
    range(11,12): f"1 goblin boss with {dice('1d4')} dire wolves and {dice('2d6')} goblins",
    13: f"{dice('1d6')} giant elk",
    range(14,15): f"{dice('1d8') + 1} giant eagles",
    range(16,17): f"{dice('1d4')} phase spiders",
    range(18,19): f"1 gnoll pack lord with {dice('2d4')} giant hyenas",
    20: f"{dice('2d4')} hippogriffs",
    range(21,25): f"A 15 foot tall stone statue of a dwarf warrior that has been tipped over on its side",
    range(26,27): f"{dice('2d4')} orogs",
    range(28,29): f"{dice('1d4') + 1} griffons",
    range(30,31): f"{dice('1d6') + 2} harpies",
    range(32,33): f"1 ore Eye ofGruumsh with {dice('2d6') + 3} ores",
    range(34,35): f"{dice('1d4') + 3} giant boars",
    range(36,40): f"A stone door set into the side of a steep hill,opening onto 5 feet of descending stairs that end at a cave in",
    range(41,42): f"{dice('1d3')} green hags",
    range(43,44): f"{dice('1d4')} werewolves",
    range(45,46): f"{dice('1d6') + 2} ogres",
    range(47,48): f"1 hobgoblin captain with {dice('2d8')} hobgoblins",
    range(49,50): f"1 bandit captain with {dice('3d6')} bandits",
    range(51,54): f"1 chimera",
    range(55,58): f"{dice('1d4')} ettins",
    range(59,62): f"{dice('1d6') + 2} vete rans with {dice('2d6')} berserke rs",
    range(63,65): f"An abandoned wooden hut",
    range(66,69): f"1 galeb duhr",
    range(70,73): f"1 bulette",
    range(74,77): f"1 wyvern",
    range(78,80): f"{dice('2d6') + 10} goats with 1 herder (tribal warrior)",
    range(81,82): f"{dice('1d3')} hill giants",
    range(83,84): f"{dice('2d4')} wereboars",
    range(85,86): f"{dice('1d4')} reve nants",
    range(87,88): f"{dice('1d2')} gorgons",
    range(89,90): f"{dice('1d8') + 1} gnoll fangs ofYeenoghu",
    range(91,93): f"{dice('1d4')} cyclopes",
    range(94,96): f"1 young red dragon",
    range(97,98): f"{dice('1d4')} stone giants",
    99: f"{dice('1d3')} young copper dragons",
    100: f"1 roe"
})
encounter_hills_11_16 = expand({
    1: f"{dice('2d8')} manticores or {dice('2d8')} phase spiders",
    range(2,4): f"{dice('1d6')} green hags with {dice('1d6')} wyverns",
    range(5,7): f"1 hobgoblin captain with 1 hill giant and {dice('4d10')} hobgoblins",
    range(8,10): f"{dice('2d6') + 3} werewolves",
    range(11,14): f"{dice('1d6') + 2} ettins",
    range(15,18): f"1 d 3 bu lettes",
    range(19,22): f"{dice('1d4')} werebears",
    range(23,24): f"A stream of smoke emerging from a small chimney in the hillside",
    range(25,28): f"{dice('1d4')} wyverns",
    range(29,32): f"{dice('1d8') + 1} wereboars",
    range(33,36): f"{dice('1d3')} revenants",
    range(37,38): f"A miId earthquake that shakes the region for {dice('1d20')} seconds",
    range(39,42): f"{dice('1d3')} chimeras",
    range(43,46): f"{dice('1d4')} gorgons",
    range(47,50): f"{dice('1d6') + 2} gnoll fangs ofYeenoghu",
    range(51,54): f"{dice('1d4')} hill giants",
    range(55,58): f"1 young red dragon",
    range(59,62): f"{dice('1d3') + 1} galeb duhr",
    range(63,65): f"{dice('2d10')} dwarf miners (commoners),whistling as they march toward their mine",
    range(66,69): f"{dice('1d3')} young copper dragons 1",
    range(70,73): f"{dice('1d4')} trolls",
    range(74,77): f"{dice('1d3')} cyclopes",
    range(78,80): f"{dice('1d3')} nobles with {dice('1d4')} scouts prospecting for goId",
    range(81,85): f"1 adult copper dragon",
    range(86,90): f"{dice('2d4')} stone giants",
    range(91,96): f"{dice('1d4')} roes",
    range(97,99): f"1 adult red dragon",
    100: f"1 ancient copper dragon"
})
encounter_hills_17_20 = expand({
    1: f"{dice('1d2')} roes",
    range(2,5) : f"1 young red dragon",
    range(6,10): f"{dice('2d6')} ettins",
    range(11,15): f"{dice('1d4')} bulettes",
    range(16,20): f"1 dl 0 revenants",
    range(21,25): f"The white outline of an enormous horse carved into the side of a high hill",
    range(26,30): f"{dice('1d6') + 1} gorgons",
    range(31,35): f"{dice('2d4') + 1} trolls",
    range(36,40): f"The scorched remains of {dice('2d10')} humanoids littering a hillside",
    range(41,45): f"{dice('2d4')} hill giants",
    range(46,50): f"{dice('1d6') + 2} werebears",
    range(51,55): f"{dice('2d4')} galeb duhr",
    range(56,60): f"{dice('1d4') + 2} wyverns",
    range(61,65): f"A massive bouIder partly buried in the earth as if it fell or was thrown there",
    range(66,70): f"1 adult copper dragon",
    range(71,75): f"{dice('1d6') + 3} cyclopes",
    range(76,80): f"The stub of an oId stone tower jutting from the top ofa hill",
    range(81,85): f"{dice('2d4')} stone giants",
    range(86,90): f"1 adult red dragon",
    range(91,96): f"1 ancient copper dragon",
    range(97,99): f"1 ancient red dragon",
    100: f"{dice('1d2')} adult red dragons with {dice('1d3')} young red dragons"
})
encounter_mountain_1_4 = expand({
    range(1,2): f"1 eagle",
    range(3,5): f"{dice('1d3')} swarms of bats",
    range(6,8): f"{dice('1d6')} goats",
    range(9,11): f"{dice('1d10') + 5} tribal warriors",
    range(12,14): f"{dice('1d6') + 3} pteranodons",
    range(15,17): f"{dice('1d8') + 1} winged koboIds",
    range(18,20): f"1 lion",
    range(21,24): f"Stairs chiseled into the side of the mountain that climb {dice('3d20') + 40} feet before ending abruptly",
    range(25,27): f"{dice('2d10')} stirges",
    range(28,30): f"{dice('2d4')} aarakocra",
    range(31,33): f"{dice('2d6')} dwarf soIdiers (guards) with {dice('1d6')} mules laden with iron ore",
    range(34,36): f"1 giant eagle",
    range(37,38): f"A small shrine dedicated to a lawful neutral god,perched on a stone outcropping",
    range(39,41): f"{dice('2d8') + 1} blood hawks",
    range(42,44): f"1 giant goat",
    range(45,47): f"{dice('3d4')} koboIds",
    range(48,50): f"1 half ogre",
    range(51,53): f"1 berserker",
    range(54,55): f"1 orog",
    56: f"1 hell hound",
    57: f"1 druid",
    range(58,59): f"1 peryton",
    range(60,61): f"{dice('1d2')} hippogriffs",
    62: f"1 manticore",
    range(63,64): f"{dice('1d6') + 2} scouts",
    range(65,67): f"Enormous footprints left by a giant,which head into the mountain peaks",
    range(68,73): f"{dice('2d4')} ores",
    range(74,75): f"1 giant elk",
    range(76,77): f"1 veteran",
    range(78,79): f"1 ore Eye ofGruumsh",
    80: f"{dice('1d4')} harpies",
    81: f"1 ogre",
    82: f"1 griffon",
    83: f"1 basilisk",
    range(84,85): f"1 saber toothed tiger",
    range(86,90): f"A sparkling stream of water spilling from a crevice",
    91: f"{dice('1d2')} ettins",
    92: f"1 cyclops",
    93: f"1 troll",
    94: f"1 galeb duhr",
    95: f"1 air elemental",
    96: f"1 bulette",
    97: f"1 chimera",
    98: f"1 wyvern",
    99: f"1 stone giant",
    100: f"1 frost giant"
})
encounter_mountain_5_10 = expand({
    range(1,2): f"{dice('2d8') + 1} aarakocra",
    range(3,4) : f"1 lion or 1 saber toothed tiger",
    range(5,6): f"{dice('1d8') + 1} giant goats",
    range(7,8): f"{dice('1d4') + 3} dwarf trailblazers (scouts)",
    range(9,10): f"{dice('1d6') + 2} ores",
    range(11,15): f"{dice('1d10')} giant eagles",
    range(16,20): f"{dice('1d8') + 1} hippogriffs",
    range(21,25): f"{dice('1d8')} fissures venting steam that partially obscures a 20 foot cube above each fissure",
    range(26,30): f"1 basilisk",
    range(31,35): f"{dice('1d12')} half orgres",
    range(36,40): f"A ravine blocked by a 100 foot high wall,which has an opening in the center where a gate used to be",
    range(41,45): f"1 manticore",
    range(46,50): f"{dice('2d4')} harpies",
    range(51,52): f"1 galeb duhr",
    range(53,54): f"1 bulette",
    range(55,56): f"{dice('1d10')} berserkers",
    range(57,58): f"{dice('1d3')} hell hounds",
    range(59,60): f"{dice('1d8') + 1} veterans",
    range(61,65): f"A distant mountain whose peak resembles a tooth",
    range(66,69): f"{dice('1d4')} ettins",
    range(70,73): f"1 wyvern",
    range(74,75): f"1 ore Eye ofGruumsh with {dice('1d6')} orogs and {dice('3d6') + 10} ores",
    range(76,80): f"A row of {dice('1d10') + 4}0 stakes upon which the bodies of koboIds,dwarves,or ores are impaled",
    range(81,83): f"1 fire giant",
    range(84,85): f"1 young silver dragon",
    range(86,87): f"{dice('1d4')} air elementals",
    range(88,90): f"{dice('1d4')} trolls",
    range(91,92): f"{dice('1d3') + 1} cyclopes",
    range(93,94): f"{dice('1d4')} chimeras",
    range(95,96): f"1 cloud giant",
    97: f"1 roe",
    98: f"{dice('1d4')} stone giants",
    99: f"1 young red dragon",
    100: f"{dice('1d4')} frost giants"
})
encounter_mountain_11_16 = expand({
    range(1,2): f"{dice('1d8') + 1} basilisks",
    range(3,4): f"{dice('2d4')} hell hounds",
    range(5,6): f"{dice('1d3')} chimeras",
    range(7,8): f"1 galeb duhr",
    range(9,10): f"{dice('2d6')} veterans",
    range(11,15): f"1 young silver dragon",
    range(16,20): f"{dice('2d4')} trolls",
    range(21,25): f"1 red dragon gliding through the sky above the highest mountaintops",
    range(26,30): f"{dice('1d8') + 1} manticores",
    range(31,35): f"{dice('1d4')} cyclopes",
    range(36,40): f"Heavy snowfall that lasts for {dice('1d6')} hours",
    range(41,45): f"{dice('1d10')} air elementals",
    range(46,50): f"{dice('1d6') + 2} bulettes",
    range(51,55): f"{dice('1d4')} stone giants",
    range(56,60): f"1 fire giant",
    range(61,65): f"2 stone giants playing catch with a bouIder a few hundred feet away",
    range(66,70): f"{dice('1d8') + 1} ettins",
    range(71,75): f"{dice('1d3')} frost giants",
    range(76,80): f"A wide crevasse,its depths shrouded in mist",
    range(81,85): f"{dice('1d4')} cloud giants",
    range(86,90): f"1 adult silver dragon",
    range(91,96): f"1 adult red dragon",
    range(97,98): f"{dice('1d4')} roes",
    99: f"1 ancient silver dragon",
    100: f"1 ancient red dragon"
})
encounter_mountain_17_20 = expand({
    range(1,5): f"{dice('1d10')} bulettes",
    range(6,10): f"{dice('1d8') + 1} chimeras",
    range(11,15): f"1 adult silver dragon",
    range(16,20): f"{dice('1d8') + 1} wyverns",
    range(21,25): f"A massive boat perched atop a mountain",
    range(26,30): f"{dice('2d4')} galeb duhr",
    range(31,35): f"{dice('1d4')} frost giants",
    range(36,40): f"A wooded valley haunted by secretive and reclusive elves who tell warily of their master: a mad wiza rd who lives in the heart of the va lley",
    range(41,45): f"{dice('1d10')} air elementals",
    range(46,50): f"{dice('1d6') + 3} trolls",
    range(51,55): f"1 adult red dragon",
    range(56,60): f"{dice('1d4')} cloud giants",
    range(61,65): f"A waterfall hundreds offeet high that drops into a clear pool",
    range(66,70): f"{dice('1d3')} fire giants",
    range(71,75): f"{dice('2d4')} stone giants",
    range(76,80): f"A force of 100 dwarves (veterans) st anding guard at a mountain pass,permitting no passage until a traveler pays 100 gp (if on foot) Or 200 gp (if mounted)",
    range(81,85): f"{dice('1d4')} roes",
    range(86,90): f"{dice('1d4')} young red dragons",
    range(91,96): f"1 ancient silver dragon",
    range(97,100): f"1 ancient red dragon"
})
encounter_swamp_1_4 = expand({
    1: f"{dice('1d4')} poisonous snakes",
    range(2,5): f"{dice('3d6')} rats",
    range(6,10): f"{dice('2d8')} ravens",
    range(11,12): f"{dice('3d6')} giant rats",
    13: f"{dice('1d10') + 5} tribal warriors",
    range(14,15): f"{dice('1d8') + 1} giant lizards",
    range(16,17): f"1 crocodile",
    range(18,19): f"1 swarm of insects",
    20: f"1 giant spider",
    range(21,22): f"{dice('1d4') + 1} mud huts partially sunken in murky water",
    range(23,25): f"{dice('2d8') + 1} koboIds",
    26: f"{dice('2d4')} mud mephits",
    range(27,29): f"{dice('1d6') + 2} giant poisonous snakes",
    30: f"{dice('2d4')} winged koboIds",
    range(31,32): f"1 scout",
    range(33,34): f"The corpse of an adventurer tangled in the weeds. Looting the body turns up an explorer's pack and perhaps (50% chance) A random common magic item.",
    range(35,38): f"1 giant toad",
    range(39,41): f"{dice('1d6') + 2} constrictor snakes",
    range(42,44): f"{dice('2d4')} giant frogs",
    45: f"{dice('1d8') + 1} swarms of rats or {dice('1d6') + 2} swarms of ravens",
    range(46,48): f"{dice('2d10')} stirges",
    range(49,52): f"{dice('2d6') + 3} bullywugs",
    range(53,54): f"{dice('1d8') + 1} ores",
    range(55,56): f"{dice('1d4')} yuan ti purebloods",
    57: f"1 druid",
    range(58,59): f"1 yuan ti malison",
    range(60,62): f"1 giant constrictor snake",
    range(63,64): f"A high pitched shriek that lasts for {dice('1d4')} minutes",
    range(65,67): f"{dice('2d4')} lizardfolk",
    range(68,69): f"{dice('1d4')} ghouls",
    range(70,71): f"1 will o'wisp",
    72: f"1 wight",
    73: f"1 ghast",
    range(74,75): f"1 swarm of poisonous snakes",
    range(76,77): f"A foul stench bubbling up from brackish waters",
    range(78,80): f"{dice('1d4') + 2} ogres",
    range(81,83): f"1 shambling mound",
    range(84,86): f"1 fizardfolk shaman with {dice('1d6')} giant lizards and {dice('2d10')} lizardfolk",
    87: f"1 troll",
    range(88,89): f"{dice('1d4')} green hags",
    range(90,91): f"1 revenant",
    range(92,93): f"1 giant crocodile",
    range(94,95): f"1 ore Eye ofGruumsh with {dice('1d3')} orogs and {dice('2d6') + 3} ores",
    range(96,97): f"1 young black dragon",
    98: f"1 yuan ti abomination",
    99: f"{dice('1d4')} water elementals",
    100: f"1 hydra"
})
encounter_swamp_5_10 = expand({
    1: f"1 green hag",
    range(2,3): f"{dice('2d4')} giant lizards or {dice('2d4')} giant poisonous snakes",
    range(4,5): f"{dice('2d8')} winged koboIds",
    range(6,7): f"{dice('1d10') + 1} bullywugs with {dice('1d8') + 1} giant frogs",
    range(8,9): f"1 druid",
    10: f"{dice('1d8') + 1} swarms of insects",
    range(11,13): f"{dice('1d12')} ghouls",
    range(14,16): f"{dice('2d8')} scouts",
    range(17,19): f"{dice('2d10')} ores",
    range(20,22): f"{dice('2d4')} giant spiders",
    range(23,24): f"Tainted water that exposes creatures that move through it to sight rot",
    range(25,27): f"{dice('1d6') + 2} giant toads",
    range(28,30): f"{dice('3d6')} lizardfolk",
    range(31,33): f"{dice('1d8') + 1} yuan ti purebloods",
    range(34,36): f"{dice('1d4') + 1} swarms of poisonous snakes",
    range(37,38): f"A bloated humanoid corpse floating facedown in the water",
    range(39,41): f"1 shambling mound",
    range(42,44): f"{dice('1d4') + 1} will o'wisps",
    range(45,47): f"{dice('2d6')} crocodiles",
    range(48,50): f"{dice('1d4') + 1} giant constrictor snakes",
    range(51,54): f"1 lizardfolk shaman with {dice('1d3')} swarms of poisonous snakes and {dice('1d8') + 2} lizardfolk",
    range(55,58): f"{dice('1d8') + 1} ogres",
    range(59,62): f"{dice('2d4')} ghasts",
    range(63,65): f"An altar partially sunk into the mud,devoted to a god that is part human and part frog",
    range(66,69): f"1 giant crocodile",
    range(70,73): f"1 shambling mound",
    range(74,77): f"1 ore Eye ofGruumsh with {dice('1d3')} ogres and {dice('2d10') + 5} ores",
    range(78,80): f"A torrential rain that lasts {dice('1d6')} minutes and puts out all unprotected flames within 1 mile",
    range(81,82): f"1 young black dragon",
    range(83,84): f"{dice('1d4')} green hags with {dice('1d6') + 1} ogres",
    range(85,86): f"1 yuan ti abomination",
    range(87,88): f"{dice('1d4') + 1} wights",
    range(89,90): f"{dice('1d6') + 1} yuan ti malisons",
    range(91,93): f"{dice('1d4') + 1} trolls",
    range(94,96): f"{dice('1d10')} revenants",
    range(97,99): f"{dice('1d8') + 1} water elementals",
    100: f"{dice('1d3')} hydras"
})
encounter_swamp_11_20 = expand({
    range(1,10): f"{dice('1d4')} giant crocodiles",
    range(11,15): f"{dice('1d3')} yuan ti abominations",
    range(16,20): f"{dice('1d6') + 1} green hags",
    range(21,25): f"A large,spreading tree from which {dice('2d6')} armored knights hang by the neck",
    range(26,30): f"{dice('2d4')} wights",
    range(31,35): f"{dice('1d8') + 1} yuan ti malisons",
    range(36,40): f"Fog that rolls across the terrain,making the area within {dice('1d3')} miles heavily obscured for {dice('1d4')} hours",
    range(41,45): f"{dice('1d4')} revenants",
    range(46,50): f"{dice('1d6')} shambling mounds",
    range(51,55): f"{dice('1d10')} water elementals",
    range(56,60): f"{dice('1d4')} young black dragons",
    range(61,65): f"An eerie,bat headed idol almost completely covered by vines",
    range(66,70): f"{dice('1d8') + 2} trolls",
    range(71,75): f"{dice('1d3')} hydras",
    range(76,80): f"The sound of drums beating several miles away",
    range(81,96): f"1 adult black dragon",
    range(97,100): f"1 ancient black dragon"
})
encounter_underdark_1_4 = expand({
    1: f"1 mind flayer arcanist",
    2: f"{dice('1d3') + 1} giant poisonous snakes",
    3: f"{dice('1d3')} giant lizards",
    4: f"{dice('2d4')} giant fire beetles",
    5: f"{dice('1d8') + 1} flumphs",
    6: f"1 shrieker",
    7: f"{dice('1d12')} giant rats",
    8: f"{dice('2d4')} koboIds",
    9: f"{dice('1d8') + 1} stirges",
    10: f"{dice('2d4')} humans (tribal warriors) seeking the way to the surface,fleeing their Underdark oppressors",
    range(11,12): f"{dice('1d10')} troglodytes",
    range(13,14): f"{dice('1d2')} gray oozes",
    range(15,16): f"{dice('3d6')} stirges",
    range(17,18): f"{dice('1d3')} magma mephits",
    range(19,20): f"{dice('1d10')} goblins",
    range(21,22): f"Ore graffiti on the walls,suggesting something rude about the mother of someone named Krusk",
    range(23,24): f"1 swarm of insects",
    25: f"1 deep gnome ",
    range(26,28): f"{dice('1d8') + 1} drow ",
    range(29,30): f"{dice('1d4')} violet fungi ",
    range(31,32): f"{dice('1d12')} kuo toa ",
    33: f"1 rust monster ",
    range(34,35): f"A rubble strewn passage that appears to have been recently cleared after a cave in ",
    range(36,37): f"{dice('1d8') + 1} giant bats ",
    range(38,39): f"{dice('3d6')} koboIds ",
    range(40,41): f"{dice('2d4')} grimlocks ",
    range(42,43): f"{dice('1d4') + 3} swarms of bats ",
    44: f"1 dwarf prospector (scout) looking for goId ",
    45: f"1 carrion crawler or 1 gelatinous cube ",
    46: f"{dice('1d8')} darkmantles or {dice('2d4')} piercers ",
    47: f"1 hell hound ",
    48: f"{dice('1d3')} specters",
    49: f"{dice('1d4')} bugbears ",
    50: f"{dice('1d10') + 5} winged koboIds ",
    51: f"{dice('1d4')} fire snakes ",
    52: f"{dice('2d8') + 1} troglodytes ",
    53: f"{dice('1d6')} giant spiders ",
    54: f"{dice('3d6')} kuo toa ",
    55: f"1 goblin boss with {dice('2d4')} goblins ",
    56: f"{dice('4d4')} grimlocks ",
    57: f"1 ochre jelly ",
    58: f"{dice('2d10')} giant centipedes ",
    59: f"1 nothic or 1 giant toad ",
    60: f"{dice('1d4')} myconid adults with {dice('5d4')} myconid sprouts ",
    61: f"1 minotaur skeleton or 1 minotaur ",
    62: f"{dice('3d6')} drow ",
    63: f"1 mimic or 1 doppelganger ",
    64: f"{dice('1d6') + 3} hobgoblins ",
    65: f"1 intellect devourer or 1 spectator ",
    66: f"{dice('1d8') + 1} ores ",
    range(67,68): f"A faint tapping coming from inside a nearby wall ",
    69: f"1 gibbering mouther or 1 water weird ",
    70: f"{dice('1d12')} gas spores ",
    71: f"1 giant constrictor snake ",
    72: f"{dice('1d10')} shadows ",
    73: f"{dice('1d3')} grells ",
    74: f"{dice('1d4')} wights ",
    75: f"{dice('1d8') + 1} quaggoth spore servants ",
    76: f"{dice('1d2')} gargoyles ",
    77: f"{dice('1d4')} ogres or {dice('1d3')} ettins ",
    78: f"{dice('1d4')} dwarf explorers (veterans) ",
    range(79,80): f"An abandoned miners' camp spattered with blood and littered with the contents of {dice('1d3')} dungeoneer's packs ",
    81: f"1 chuul or 1 salamander ",
    82: f"{dice('1d4')} phase spiders or {dice('1d3')} hook horrors ",
    83: f"{dice('5d4')} duergar ",
    84: f"1 ghost or 1 flameskull or 1 wraith",
    85: f"1 druid with 1 polar bear (cave bear)",
    86: f"1 hobgoblin captain with {dice('1d4')} half orgres and {dice('2d10')} hobgoblins",
    87: f"1 earth elemental or 1 black pudding",
    88: f"1 kuo toa monitor with {dice('1d8') + 1} kuo toa whips",
    89: f"1 quaggoth thonot with {dice('1d3')} quaggoths",
    90: f"1 behoIder zombie or 1 bone naga",
    91: f"1 ore Eye ofGruumsh with {dice('1d4')} orogs and {dice('2d8')} ores",
    92: f"{dice('1d4')} ghasts with {dice('1d10')} ghouls",
    range(93,95): f"A reeking puddle where slimy water has dripped from the ceiling",
    96: f"1 otyugh or 1 roper",
    97: f"1 vampire spawn",
    98: f"1 chimera",
    99: f"1 mind flayer",
    100: f"1 spirit naga"
})
encounter_underdark_5_10 = expand({
    1: f"{dice('3d6')} swarms of bats",
    2: f"{dice('1d4')} giant spiders or {dice('1d4')} giant toads",
    3: f"1 mimic",
    4: f"{dice('2d4')} gray oozes",
    5: f"{dice('2d10')} ores or {dice('3d6')} troglodytes",
    6: f"{dice('3d6')} grimlocks",
    7: f"{dice('1d6') + 2} magma mephits",
    8: f"1 goblin boss with {dice('2d4')} goblins",
    9: f"{dice('2d4')} darkmantles",
    10: f"{dice('2d8') + 1} drow",
    11: f"{dice('2d10')} piercers",
    12: f"{dice('1d4')} minotaur skeletons",
    range(13,14): f"{dice('3d6')} deep gnomes",
    15: f"1 druid with 1 polar bear (cave bear)",
    range(16,17): f"{dice('3d6')} ores",
    18: f"1 bone naga",
    range(19,20): f"{dice('2d6')} bugbears",
    range(21,25): f"Luminescent fungi growing on the walls of a moist cave,filling it with dim light",
    26: f"{dice('2d4')} specters",
    27: f"{dice('1d12') + 4} shadows",
    28: f"{dice('1d3')} gibbering mouthers",
    range(29,30): f"{dice('4d4')} hobgoblins",
    range(31,32): f"{dice('1d4')} carrion crawlers",
    range(33,34): f"1 black pudding",
    35: f"{dice('1d4')} ochre jellies",
    range(36,40): f"A patch of moId that appears yellow when light is directed toward it",
    41: f"{dice('1d4')} nothics",
    range(42,43): f"{dice('2d8') + 1} gas spores",
    range(44,45): f"{dice('1d3')} gelatinous cubes",
    46: f"1 ghost",
    range(47,48): f"1 flameskull",
    range(49,50): f"{dice('2d8')} duergar",
    51: f"1 wraith",
    52: f"1 umber hulk",
    53: f"1 xorn",
    54: f"{dice('1d6') + 2} dwarf hunters (veterans) searching for trolls",
    55: f"1 hobgoblin captain with {dice('3d10')} hobgoblins",
    56: f"1 roper",
    57: f"1 kuo toa monitor with {dice('1d4')} kuo toa whips and {dice('1d8') + 1} kuo toa",
    58: f"{dice('1d3')} water weirds",
    59: f"{dice('1d4')} ghasts with {dice('1d10')} ghouls",
    60: f"1 otyugh",
    range(61,62): f"A merchant caravan consisting of 1 drow mage,2 drow elite warriors,and {dice('2d10')} quaggoths",
    63: f"{dice('1d4')} wights",
    64: f"{dice('1d4')} doppelgangers",
    65: f"{dice('2d8')} fire snakes",
    66: f"{dice('1d4')} spectators",
    67: f"1 ore Eye ofGruumsh with {dice('1d4')} orogs and {dice('2d10') + 3} ores",
    68: f"{dice('1d3')} vampire spawn",
    69: f"{dice('1d4')} hook horrors or {dice('1d4')} minotaurs",
    70: f"{dice('3d6')} quaggoth spore servants",
    range(71,72): f"{dice('1d3')} grells",
    73: f"{dice('1d6') + 1} intellect devourers",
    74: f"{dice('1d10')} gargoyles",
    75: f"1 behoIder zombie",
    range(76,77): f"1 quaggoth thonot with {dice('2d4')} quaggoths",
    78: f"{dice('1d6')} ettins or {dice('1d4')} trolls",
    79: f"{dice('1d8') + 1} phase spiders",
    80: f"1 fomorian or {dice('1d3')} cyclopes",
    81: f"{dice('1d4')} earth elementals",
    82: f"{dice('3d6')} ogres",
    83: f"{dice('1d4') + 1} chuuls",
    84: f"{dice('1d10')} hell hounds",
    85: f"{dice('1d3')} drow elite warriors",
    86: f"{dice('1d4')} chimeras",
    87: f"{dice('1d4')} salamanders",
    88: f"1 cloaker",
    89: f"{dice('2d4')} wights",
    90: f"{dice('1d4')} driders",
    91: f"1 fire giant",
    92: f"1 grick alpha with {dice('2d4')} gricks",
    93: f"1 mind flayer arcanist",
    94: f"{dice('1d4')} drow mages",
    95: f"1 spirit naga",
    96: f"{dice('1d4')} mind flayers",
    97: f"1 behir",
    98: f"1 aboleth",
    99: f"1 dao or 1 stone giant",
    100: f"1 behoIder"
})
encounter_underdark_11_16 = expand({
    range(1,2): f"{dice('3d6')} carrion crawlers",
    range(3,4): f"{dice('1d6') + 1} gelatinous cubes",
    range(5,6): f"{dice('1d8') + 2} gibbering mouthers",
    range(7,8): f"{dice('2d8')} minotaur skeletons",
    range(9,10): f"{dice('2d6')} ochre jellies",
    range(11,12): f"{dice('2d4')} doppelgangers",
    range(13,14): f"{dice('1d4')} quaggoth thonots with {dice('1d10') + 2} quaggoths",
    range(15,16): f"{dice('1d3')} ropers",
    range(17,18): f"{dice('3d6')} gargoyles",
    range(19,20): f"{dice('1d10')} mimics",
    range(21,25): f"A 100 foot long ravine,{dice('4d10')} feet wide and {dice('5d20') + 200} feet deep",
    range(26,27): f"1 hobgoblin captain with {dice('3d10')} hobgoblins",
    range(28,29): f"{dice('2d4')} spectators",
    range(30,31): f"{dice('3d6')} ghasts",
    range(32,33): f"{dice('2d8')} intellect devourers",
    range(34,35): f"{dice('1d3')} ore Eyes ofGruumsh with {dice('2d4')} orogs and {dice('2d10')} ores",
    range(36,40): f"A large cave containing {dice('2d10')} extraordinarily detailed statues of various creatures",
    range(41,42): f"{dice('1d8') + 1} kuo toa monitors",
    range(43,44): f"{dice('2d4')} water weirds",
    range(45,46): f"{dice('2d10')} gricks",
    range(47,48): f"{dice('3d6')} nothics",
    range(49,50): f"{dice('2d8') + 1} ogres",
    range(51,52): f"{dice('1d6') + 2} chuuls",
    range(53,54): f"{dice('1d8') + 1} ettins",
    55: f"{dice('3d6')} grells",
    56: f"{dice('2d4')} flameskulls",
    57: f"{dice('2d12')} dwarf soIdiers (veterans) On patrol",
    58: f"{dice('2d8')} hell hounds",
    59: f"{dice('1d10')} ghosts",
    60: f"{dice('3d4')} wights",
    61: f"{dice('3d6')} phase spiders",
    62: f"{dice('1d8') + 1} bone nagas",
    range(63,65): f"A shrill scream followed by dark laughter",
    66: f"{dice('1d4')} chimeras",
    67: f"{dice('1d10')} black puddings",
    68: f"{dice('3d6')} minotaurs",
    69: f"{dice('2d4')} otyughs",
    70: f"{dice('1d6') + 1} behoIder zombies",
    71: f"{dice('4d4')} hook horrors",
    72: f"{dice('1d8') + 1} umber hulks",
    73: f"{dice('2d4')} salamanders",
    74: f"{dice('1d3')} grick alphas",
    75: f"{dice('1d6') + 2} xorn",
    range(76,80): f"A ruined village that once belonged to deep gnomes. A search has a 50% chance of uncovering {dice('1d3')} potions of healing and a 25% chance of finding a random common magic item.",
    81: f"{dice('2d4')} earth elementals",
    82: f"{dice('1d3')} spirit nagas",
    83: f"{dice('1d8') + 1} cyclopes",
    84: f"{dice('1d6') + 2} trolls",
    85: f"{dice('2d4')} stone giants",
    86: f"{dice('2d4')} wraiths",
    87: f"{dice('1d4')} fomorians",
    88: f"{dice('1d3')} drow mages with {dice('1d4')} drow elite warriors",
    89: f"{dice('1d10')} vampire spawn",
    90: f"{dice('1d3')} cloakers",
    91: f"{dice('1d4')} fire giants",
    92: f"1 mind flayer arcanist with {dice('1d6') + 1} mind flayers",
    93: f"{dice('1d4')} dao",
    94: f"{dice('1d8') + 1} driders",
    95: f"{dice('1d3')} behirs",
    96: f"{dice('1d4')} aboleths",
    97: f"1 behoIder",
    98: f"1 young red shadow dragon",
    99: f"1 death tyrant",
    100: f"1 purple worm"
})
encounter_underdark_17_20 = expand({
    1: f"{dice('1d4')} grick alphas",
    2: f"{dice('2d8')} spectators",
    range(3,4): f"{dice('3d6')} minotaurs or {dice('2d8')} kuo toa monitors",
    range(5,6): f"{dice('2d8')} grells",
    range(7,8): f"{dice('2d10')} phase spiders",
    range(9,10): f"{dice('4d4')} hell hounds",
    range(11,12): f"{dice('1d6') + 2} ropers",
    range(13,14): f"{dice('2d10')} wights",
    range(15,16): f"{dice('3d6')} doppelgangers",
    range(17,18): f"{dice('1d8') + 1} chimeras",
    range(19,20): f"{dice('1d4')} cloakers",
    21: f"{dice('1d4')} hobgoblin captains with {dice('5d10')} hobgoblins",
    range(22,23): f"{dice('1d8') + 1} earth elementals",
    range(24,25): f"{dice('2d4')} vampire spawn",
    range(26,27): f"{dice('3d6')} minotaurs",
    range(28,30): f"A 30 foot tall inverted black pyramid floating 1 inch above the floor in a large cave",
    range(31,32): f"{dice('1d10')} behoIder zombies",
    range(33,34): f"{dice('1d4')} mind flayer arcanists",
    range(35,36): f"{dice('1d6') + 2} otyughs",
    range(37,38): f"{dice('1d12')} trolls",
    range(39,40): f"{dice('1d10')} wraiths",
    range(41,43): f"A beautiful obsidian sculpture of a panther lying on the floor",
    range(44,45): f"{dice('1d4')} drow mages with {dice('1d6')} drow elite warriors",
    range(46,47): f"{dice('1d4')} spirit nagas",
    range(48,49): f"{dice('1d8') + 1} salamanders",
    range(50,51): f"{dice('2d4')} umber hulks",
    range(52,53): f"{dice('1d10')} xorn",
    range(54,56): f"1 young red shadow dragon",
    range(57,59): f"{dice('2d4')} fomorians",
    range(60,62): f"{dice('1d8') + 1} driders",
    range(63,65): f"{dice('1d20') + 20} spiders crawli ng on the walls of a webfilled cave",
    range(66,68): f"{dice('1d4')} fire giants",
    range(69,70): f"{dice('1d10')} mind flayers",
    range(71,73): f"{dice('2d4')} stone giants",
    range(74,76): f"{dice('1d12')} cyclopes",
    range(77,80): f"A large cave in which stands a 50 foot tall idol of Blibdoolpoolp",
    range(81,85): f"{dice('1d3')} dao",
    range(86,90): f"{dice('1d4')} behoIders",
    range(91,93): f"{dice('1d4')} behirs",
    range(94,96): f"1 death tyrant",
    range(97,99): f"{dice('1d3')} purple worms",
    100: f"{dice('2d4')} aboleths"
})
encounter_underwater_1_4 = expand({
    range(1,10): f"{dice('3d6')} quippers",
    range(11,14): f"{dice('2d4')} steam mephits",
    range(15,18): f"{dice('1d4')} sahuagin",
    range(19,22): f"{dice('2d6')} merfolk",
    range(23,25): f"{dice('2d4')} corpses of drowned sailors tangled in kelp",
    range(26,29): f"{dice('2d4')} constrictor snakes",
    range(30,33): f"{dice('1d4')} reef sharks",
    range(34,37): f"1 swarm of quippers",
    range(38,40): f"A bed of enormous clams",
    range(41,45): f"{dice('1d10')} merfolk with {dice('1d3')} giant sea horses",
    range(46,50): f"1 giant octopus",
    range(51,55): f"1 merrow",
    range(56,60): f"1 plesiosaurus",
    range(61,65): f"{dice('2d10')} pieces of co rroded brass dinnerware littering the bottom",
    range(66,70): f"1 giant constrictor snake",
    range(71,75): f"1 sea hag",
    range(76,80): f"A school of silvery fish darting through the water",
    range(81,85): f"{dice('1d4')} hunter sharks",
    range(86,90): f"1 sahuagin priestess with {dice('2d4')} sahuagin",
    range(91,96): f"{dice('1d4')} killer whales",
    range(97,98): f"1 giant shark",
    99: f"1 water elemental",
    100: f"1 sahuagin baron"
})
encounter_underwater_5_10 = expand({
    range(1,2): f"{dice('3d6')} steam mephits",
    range(3,4): f"{dice('1d10')} sahuagin",
    range(5,6): f"1 giant octopus",
    range(7,8): f"{dice('3d6')} constrictor snakes",
    range(9,10): f"{dice('2d10')} merfolk with {dice('1d4')} giant sea horses",
    range(11,15): f"{dice('1d4')} sea hags",
    range(16,20): f"{dice('2d4')} swarms of quippers",
    range(21,25): f"A sunken galleon with a 50% chance of a random treasure hoard inside",
    range(26,30): f"{dice('1d4')} plesiosauruses",
    range(31,35): f"{dice('3d6')} reef sharks",
    range(36,40): f"An abandoned bathysphere",
    range(41,50): f"{dice('1d4')} giant constrictor snakes",
    range(51,55): f"{dice('2d4')} hunter sharks",
    range(56,60): f"{dice('1d3')} sahuagin priestesses with {dice('2d10')} sahuagin",
    range(61,65): f"An empty castle made from coral",
    range(66,70): f"{dice('1d4')} killer whales",
    range(71,75): f"{dice('1d10')} merrow",
    range(76,80): f"An eerie statue of a squatting humanoid,with bat wings on its back and tentacles sprouting from its face",
    range(81,85): f"{dice('1d4')} water elementals",
    range(86,90): f"1 sahuagin baron with {dice('2d8')} sahuagin",
    range(91,96): f"{dice('1d4')} giant sharks",
    range(97,99): f"1 marid",
    100: f"1 storm giant"
})
encounter_underwater_11_20 = expand({
    range(1,10): f"1 sahuagin baron with {dice('1d4')} sahuagin priestesses and {dice('2d10')} sahuagin",
    range(11,35): f"{dice('1d10')} killer whales",
    range(36,40): f"A ghost ship passing overhead,containing {dice('2d6') + 10} ghosts",
    range(41,60): f"{dice('1d6')} giant sharks",
    range(61,65): f"A 1 mile radius sphere of effervescent wate r that allows air breathing creatures to breathe water while in the sphere",
    range(66,75): f"{dice('1d10')} water elementals",
    range(76,80): f"A shimmering,blue/green portal to the Elemental Plane of Water",
    range(81,90): f"{dice('1d4')} marids",
    range(91,96): f"{dice('1d3')} storm giants",
    range(97,99): f"1 dragon turtle",
    100: f"1 kraken"
})
encounter_urban_1_4 = expand({
    1: f"{dice('1d6')} cats",
    range(2,3): f"1 commoner with {dice('1d6')} goats",
    range(4,5): f"{dice('2d10')} rats",
    6: f"1 raven perched on a signpost",
    7: f"1 commoner on a draft: horse",
    8: f"{dice('2d4')} mastiffs",
    9: f"{dice('1d2')} commoners leading {dice('1d4')} mules or {dice('1d4')} ponies",
    10: f"1 pseudodragon",
    11: f"1 spy",
    range(12,13): f"{dice('1d8') + 1} acolytes",
    14: f"{dice('1d6') + 6} flying snakes",
    15: f"{dice('3d6')} koboIds",
    16: f"{dice('2d4')} giant centipedes",
    17: f"{dice('1d8') + 1} skeletons",
    range(18,19): f"{dice('1d6') + 2} swarms of rats",
    20: f"{dice('1d12')} zombies",
    range(21,25): f"A peddler weighed down with a load of pots,pans,and other basic supplies",
    26: f"1 giant wasp",
    range(27,28): f"1 warhorse",
    29: f"{dice('2d8')} cultists",
    range(30,31): f"{dice('3d4')} giant rats",
    32: f"{dice('2d8')} stirges",
    33: f"{dice('1d3') + 2} giant poisonous snakes",
    34: f"{dice('1d4') + 2} swarms of bats",
    35: f"{dice('2d4')} winged koboIds",
    range(36,40): f"A wagon loaded with apples that has a broken wheel and hoIds up traffic",
    41: f"1 crocodile",
    range(42,43): f"1 swarm of insects",
    range(44,45): f"{dice('3d6')} bandits",
    range(46,47): f"{dice('1d3') + 2} nobles on riding horses with an escort of {dice('1d10')} guards",
    48: f"{dice('2d4')} kenku",
    49: f"{dice('1d6') + 2} smoke mephits",
    50: f"{dice('1d8') + 1} swarms of ravens",
    range(51,52): f"1 wererat",
    range(53,54): f"{dice('1d3')} half.ogres",
    range(55,56): f"1 mimic",
    range(57,58): f"{dice('1d4')} ghouls",
    range(59,60): f"{dice('1d4')} specters",
    range(61,62): f"{dice('1d10')} shadows",
    range(63,65): f"Someone empties a chamber pot onto the street from a second floor window",
    range(66,67): f"1 ghast",
    range(68,69): f"1 priest",
    range(70,71): f"1 will o'wisp",
    range(72,73): f"{dice('1d3')} giant spiders",
    range(74,75): f"{dice('1d4')} yuan ti purebloods ",
    range(76,77): f"{dice('2d4')} thugs ",
    range(78,80): f"A doomsayer who preaches the end of the worId from a street corner ",
    81: f"1 cambion ",
    82: f"1 vampire spawn ",
    83: f"1 couatl ",
    84: f"1 ghost ",
    85: f"1 succubus or 1 incubus ",
    86: f"1 bandit captain with {dice('3d6')} bandits ",
    87: f"{dice('1d4') + 1} cult fanatics ",
    88: f"1 knight or 1 veteran ",
    89: f"1 water weird ",
    90: f"1 wight ",
    91: f"1 mage ",
    92: f"1 shieId guardian ",
    93: f"1 gladiator ",
    94: f"1 revenant ",
    95: f"{dice('2d4')} gargoyles ",
    96: f"{dice('1d4')} doppelgangers ",
    97: f"1 oni ",
    98: f"1 invisible stalker ",
    99: f"{dice('1d8') + 1} phase spiders ",
    100: f"1 assassin",
})
encounter_urban_5_10 = expand({
    range(1,2): f"{dice('1d10')} kenku ",
    range(3,4): f"{dice('2d6')} giant centipedes",
    range(5,6): f"{dice('2d8')} skeletons",
    range(7,8): f"{dice('1d6')} swarms of bats and {dice('1d6')} swarms of rats",
    range(9,10): f"{dice('3d6')} winged koboIds",
    range(11,13): f"{dice('2d4')} specters",
    range(14,16): f"{dice('1d4')} wights",
    range(17,19): f"{dice('4d4')} acolytes on draft horses",
    range(20,22): f"{dice('3d6')} giant centipedes",
    range(23,25): f"A talkative urchin,badgering passersby to serve as the ir guide through the community for a price of 1 sp",
    range(26,28): f"{dice('1d10')} spies",
    range(29,31): f"{dice('3d6')} crocodiles",
    range(32,34): f"{dice('1d6') + 2} swarms of insects",
    range(35,37): f"{dice('2d4')} smoke mephits",
    range(38,40): f"A noble shouts 'Stop! Thief!' at a fleeing scoundrel (bandit)",
    range(41,43): f"1 succubus or 1 incubus",
    range(44,46): f"{dice('1d10')} half orgres",
    range(47,49): f"{dice('2d10')} giant wasps",
    range(50,51): f"{dice('4d10')} zombies",
    range(52,53): f"{dice('1d4')} knights on warhorses",
    range(54,55): f"{dice('1d4') + 1} water weirds",
    range(56,57): f"{dice('1d8') + 1} mimics",
    range(58,59): f"{dice('2d8')} giant spiders",
    range(60,61): f"{dice('3d6')} shadows",
    range(62,65): f"An actor leans out from a second story window to call to passersby,announcing a show",
    range(66,67): f"1 bandit captain with {dice('3d8')} bandits",
    range(68,69): f"{dice('1d10')} will o'wisps",
    range(70,71): f"{dice('2d4')} priests",
    range(72,74): f"{dice('3d6')} yuan ti purebloods ",
    range(75,76): f"{dice('2d10')} thugs ",
    range(77,80): f"A fortune teller reads cards for those who pay a price of 1 sp ",
    81: f"{dice('1d3')} gladiators ",
    82: f"{dice('1d4') + 1} couatls ",
    83: f"{dice('1d8')} ghosts ",
    84: f"{dice('2d4')} doppelgange rs ",
    85: f"{dice('1d6')} +2 phase spiders ",
    86: f"{dice('2d4')} veterans ",
    87: f"{dice('1d8')} ghasts with {dice('2d6')} ghouls ",
    88: f"{dice('3d6')} gargoyles ",
    89: f"{dice('2d10')} cult fanatics ",
    90: f"{dice('3d6')} wererats ",
    91: f"1 assassin ",
    92: f"{dice('1d3')} invisible stalkers ",
    93: f"1 gray slaad ",
    94: f"1 young silver dragon ",
    95: f"{dice('1d4')} cambions or {dice('1d4')} revenants ",
    96: f"{dice('3d6')} wights ",
    97: f"1 archmage",
    98: f"{dice('2d4')} vampire spawn or {dice('1d4')} oni ",
    99: f"1 mage with 1 shieId guardian ",
    100: f"1 rakshasa or 1 vampire"
})
encounter_urban_11_16 = expand({
    1: f"1 mimic ",
    range(2,5): f"1 bandit captain with {dice('5d10')} bandits,all on riding horses ",
    range(6,10): f"{dice('1d10')} knights on warhorses (one knight is a doppelganger) ",
    range(11,13): f"{dice('1d8')} succubi or {dice('1d8')} incubi ",
    range(14,16): f"{dice('3d6')} cult fanatics ",
    range(17,19): f"{dice('1d10')} wights ",
    range(20,22): f"{dice('3d6')} wererats ",
    range(23,25): f"A distant boom followed by a plu me of smoke rising from the other side of the community ",
    range(26,28): f"{dice('1d8') + 1} ghosts ",
    range(29,31): f"{dice('2d10')} gargoyles ",
    range(32,34): f"{dice('1d6') + 2} water weirds ",
    range(35,37): f"{dice('1d4') + 4} willo'wisps ",
    range(38,40): f"Street performers putting on a puppet show,involving two puppets beating each other with sticks to the amusement of the gathered crowd ",
    range(41,43): f"{dice('2d4')} couatls ",
    range(44,46): f"{dice('2d8')} ghasts ",
    range(47,51): f"{dice('1d8') + 1} veterans ",
    range(52,55): f"{dice('3d4')} priests ",
    range(56,58): f"{dice('2d4')} cambions ",
    range(59,61): f"{dice('1d10')} revenants ",
    range(62,65): f"{dice('2d4')} phase spiders",
    range(66,69): f"A scruffy commone r that ducks into an alley to make a purchase from a suspicious looking figure",
    range(70,72): f"{dice('1d8')} invisible stalke rs",
    range(73,75): f"{dice('1d8') + 1} gladiators",
    range(76,80): f"Two farmers trading blows over the price of potatoes (50% chance for one farmer to be a retired assassin)",
    range(81,82): f"{dice('1d4')} young silver dragons",
    range(83,84): f"{dice('1d4')} assassins",
    range(85,86): f"{dice('1d8')} oni",
    range(87,88): f"{dice('1d4')} mages with {dice('1d4')} shieId guardians",
    range(89,90): f"{dice('1d10')} vampire spawn",
    range(91,92): f"1 adult silver dragon",
    range(93,94): f"{dice('1d4')} gray slaadi",
    range(95,96): f"1 spellcaster vampire or 1 warrior vampire",
    97: f"1 archmage speed ing down the street on a riding horse,blasting {dice('1d4')} guards with spells",
    98: f" 1 rakshasa",
    99: f" 1 vampire",
    100: f" 1 ancient silver dragon"
})
encounter_urban_17_20 = expand({
    range(1,5): f"{dice('1d10')} invisible stalkers",
    range(6,10): f"{dice('1d10')} revenants",
    range(11,14): f"{dice('1d6') + 2} gladiators",
    range(15,18): f"{dice('2d4')} cambions",
    range(19,22): f"{dice('2d6')} succubi or {dice('2d6')} incubi",
    range(23,25): f"A witch (archmage) who zooms overhead on a broom of flying",
    range(26,30): f"{dice('1d4')} gray slaadi",
    range(31,35): f"{dice('2d8')} couatls",
    range(36,40): f"A distraught parent who rushes up to people,begging for help for a chiId who fell into the sewer",
    range(41,45): f"{dice('1d3')} young silver dragons",
    range(46,50): f"{dice('3d6')} ghosts",
    range(51,55): f"1 adult silver dragon",
    range(56,60): f"{dice('1d4')} mages with {dice('1d4')} shieId guardians",
    range(61,65): f"An aggressive merchant who hawks wares to passersby,claiming to be the purveyor of the finest silks in all the land",
    range(66,70): f"1 ancient silver dragon",
    range(71,75): f"{dice('3d6')} vampire spawn",
    range(76,80): f"A patrol of {dice('2d10')} guards ma rching up the street,searching for someone or something",
    range(81,85): f"{dice('1d10')} assassins",
    range(86,90): f"{dice('1d4') + 1} gray slaadi",
    range(91,93): f"{dice('1d10')} oni",
    range(94,96): f"1 spellcaster vampire or 1 warrior vampire",
    97: f"{dice('1d4')} archmages",
    98: f"{dice('1d3')} rakshasas",
    99: f"{dice('1d4')} vampires",
    100: f"1 tarrasque"
})
artic = [encounter_artic_1_4, encounter_artic_5_10, encounter_artic_11_16, encounter_artic_17_20]
coastal = [encounter_coastal_1_4, encounter_coastal_5_10, encounter_coastal_11_16, encounter_coastal_17_20]
desert = [encounter_desert_1_4, encounter_desert_5_10, encounter_desert_11_16, encounter_desert_17_20]
forest = [encounter_forest_1_5, encounter_forest_5_10, encounter_forest_11_16, encounter_forest_17_20]
grassland = [encounter_grassland_1_5, encounter_grassland_6_10, encounter_grassland_11_16, encounter_grassland_17_20]
hills = [encounter_hills_1_4, encounter_hills_5_10, encounter_hills_11_16, encounter_hills_17_20]
mountain = [encounter_mountain_1_4, encounter_mountain_5_10, encounter_mountain_11_16, encounter_mountain_17_20]
swamp = [encounter_swamp_1_4, encounter_swamp_5_10, encounter_swamp_11_20]
underdark = [encounter_underdark_1_4, encounter_underdark_5_10, encounter_underdark_11_16, encounter_underdark_17_20]
underwater = [encounter_underwater_1_4, encounter_underwater_5_10, encounter_underwater_11_20]
urban = [encounter_urban_1_4, encounter_urban_5_10, encounter_urban_11_16, encounter_urban_17_20]

encounters = {'artic': artic, 'coastal': coastal, 'desert': desert, 'forest': forest, 'grassland': grassland, 
        'hills': hills, 'mountain': mountain, 'swamp': swamp, 'underdark': underdark, 'underwater': underwater, 'urban': urban}

import click
import varname

@click.command()
@click.argument('biome', default='forest')
@click.argument('level', default='0')
def get_encounter(biome, level):
    # If no level is specified, or is 0, get a random level between 1 and 20
    if level == '0':
        level_get = random.randint(1,20)
    # Otherwise use the level specified
    else:
        level_get = int(level)
    # Check for valid biome. "random" isn't a valid key but is a valid option so
    #   an exception is made here, which is worked around with the biome_check variable
    if biome not in encounters.keys():
        # Selects a random biome if 'random' is the biome type
        if biome == 'random':
            biome = random.choice(list(encounters.keys()))
            biome_check = True
        # If not "random" or a valid biome, fail
        else:
            print("invalid biome")
            biome_check = False
    else:
        biome_check = True
     
    if biome_check is True:
        # Some biome tables only have 3 lists, some have 4, this checks if the fourth list exists for the 
        #   currently selected biome. 3 list and 4 list biome tables have different level ranges for their
        #   tables, so this exception is needed
        try:
            encounters[biome][3]
            if level_get < 5:
                x = 0
            elif level_get <= 10:
                x = 1
            elif level_get <= 16:
                x = 2
            elif level_get <= 20:
                x = 3
        except IndexError:
            if level_get <= 5:
                x = 0
            elif level_get <= 10:
                x = 1
            elif level_get <=20:
                x = 2
        # Prints results
        print(f"Biome: {biome}")
        print(f"Character level: {level_get}")
        # Similar check as above, as the level ranges change depending on which biome is selected
        if biome != 'underwater' and biome != 'swamp':
            if x == 0:
                print("Level range 1-4")
            elif x==1:
                print("Level range 5-10")
            elif x==2:
                print("Level range 11-16")
            elif x==3:
                print("Level range 17-20")
        else:
        # These ranges are only for the underwater and swamp biome and thus this exception is needed
            if x==0:
                print("Level range 1-4")
            elif x == 1:
                print("Level range 5-10")
            elif x == 2:
                print("Level range 11-20")
        encounter_table = encounters[biome][x]
        encounter = random.choice(list(encounter_table))
        print(encounter_table[encounter])

if __name__ == "__main__":
    get_encounter()
